### ISSUE TITLE
pPanicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21

### ISSUE THREAD

**Issue by matsm** [NLnetLabs/routinator#107]
When running:

routinator -c /usr/local/etc/routinator.conf vrps --format rpsl -n --output rpki.db

I get

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

This is new, the command has worked daily for over a week

routinator version: latest fetched from github
os: FreeBSD 11.2-RELEASE-p7

Debug:
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: rpki::resources::ipres::IpBlocks::validate_issued
  10: rpki::cert::Cert::validate_resources
  11: rpki::cert::Cert::validate_ee_at
  12: rpki::sigobj::SignedObject::validate_at
  13: rpki::sigobj::SignedObject::validate
  14: rpki::roa::Roa::process
  15: routinator::repository::Repository::process_ca
  16: routinator::repository::Repository::process_ca
  17: routinator::repository::Repository::process_ca
  18: routinator::repository::Repository::process_ca
  19: routinator::repository::Repository::process_tal
  20: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  21: std::panicking::try::do_call
  22: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  23: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
  24: <futures_cpupool::MySender<F, core::result::Result<<F as futures::future::Future>::Item, <F as futures::future::Future>::Error>> as futures::future::Future>::poll
  25: futures::task_impl::std::set
  26: futures::task_impl::std::Run::run
  27: futures_cpupool::Inner::work

**Comment by partim** [comment]
Thanks! This is extremely helpful!

**Comment by matsm** [comment]
Some more info

RUST_BACKTRACE=full routinator -c /usr/local/etc/routinator.conf vrps --format rpsl -n --output rpki.db
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
stack backtrace:
   0:          0x1240b10 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h899bda5b98a169df
   1:          0x124c8a0 - std::sys_common::backtrace::print::h39f59893e4ebe8f0
   2:          0x1246165 - std::panicking::default_hook::{{closure}}::hc4e8c31656ad7375
   3:          0x1245ed9 - std::panicking::default_hook::hc8f0db7e9ae084e7
   4:          0x1246852 - std::panicking::rust_panic_with_hook::h4165e536bc6271da
   5:          0x1246406 - std::panicking::continue_panic_fmt::h7608cd60e175b993
   6:          0x12462f8 - rust_begin_unwind
   7:          0x129033a - core::panicking::panic_fmt::h5129b8604ac411dc
   8:          0x1290277 - core::panicking::panic::h51d16a4dbac8cae1
   9:          0x118d949 - rpki::resources::ipres::IpBlocks::validate_issued::hcb90c9513de49968
  10:          0x118fc39 - rpki::cert::Cert::validate_resources::h87664bca24ca94ff
  11:          0x118f9c9 - rpki::cert::Cert::validate_ee_at::h1e9790c3c7f9b81a
  12:          0x11840f4 - rpki::sigobj::SignedObject::validate_at::h8455d54995964e86
  13:          0x1183ddd - rpki::sigobj::SignedObject::validate::h3deb5650a693dbf0
  14:          0x109debe - rpki::roa::Roa::process::h4fb9d6cb4b12c70b
  15:          0x10e39f4 - routinator::repository::Repository::process_ca::h528c52c14a940ff0
  16:          0x10e3cd4 - routinator::repository::Repository::process_ca::h528c52c14a940ff0
  17:          0x10e3cd4 - routinator::repository::Repository::process_ca::h528c52c14a940ff0
  18:          0x10e3cd4 - routinator::repository::Repository::process_ca::h528c52c14a940ff0
  19:          0x10e194b - routinator::repository::Repository::process_tal::hb0724dca226180e7
  20:          0x1082821 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h995dd6f5e5dbcdcb
  21:          0x110ed45 - std::panicking::try::do_call::h1bbb063f83546936
  22:          0x125797e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  23:          0x10ea58e - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h47f8bb7eac2f6af1
  24:          0x10a025a - <futures_cpupool::MySender<F, core::result::Result<<F as futures::future::Future>::Item, <F as futures::future::Future>::Error>> as futures::future::Future>::poll::h8aff3e8243e4f709
  25:          0x11b6c67 - futures::task_impl::std::set::h4e6902f8cddeb327
  26:          0x11b6e02 - futures::task_impl::std::Run::run::hf7fc137856ebc81f
  27:          0x11ae3dd - futures_cpupool::Inner::work::hff5f847f1f534795
  28:          0x11af438 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5237599b9a5618d8
  29:          0x11afbc7 - std::panicking::try::do_call::h2e88e6064b20d644
  30:          0x125797e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  31:          0x11af9a5 - <F as alloc::boxed::FnBox<A>>::call_box::h1b5673fd3c49da49
  32:          0x12433de - std::sys_common::thread::start_thread::h4839100ca5f91307
  33:          0x122f2f8 - std::sys::unix::thread::Thread::new::thread_start::h563ea8dd1421580e
  34:        0x80176bc05 - pthread_create
  35:                0x0 - <unknown>

**Comment by matsm** [comment]
Even more update :)

After scratching the database and starting with an empty repository everything works again.

/mm

**Comment by partim** [comment]
Once again, thank you for providing all the data! I have now reproduced the issue with an old dump of the repository and will hopefully have a fix soon!

**Comment by partim** [comment]
This got fixed in [rpki-rs’ #30](https://github.com/NLnetLabs/rpki-rs/pull/30). A release will follow soon.
