### ISSUE TITLE
IP ACL for validator

### ISSUE THREAD

**Issue by ebais** [NLnetLabs/routinator#116]
I would like to see a way to limit, via the config file, the usage of the validator for our own routers / network prefix(es).

**Comment by wk** [comment]
Is there a compelling reason why this should be handled by the `routinator` process itself rather than at the operating system level (via `iptables` on Linux or similar), where these capabilities are both extensive and proven?

**Comment by wk** [comment]
In-daemon ACLs are the obvious choice when there's a desire to provide some form of selective service based on origin IPs (for example, MTAs which may allow relaying from some IP blocks, but only inbound mail from others), in such a scenario OS-level packet filtering may lack the necessary signalling channel to communicate such intent. This does not appear to be the case here.

When the ACL is intended to deprive all but a subset of addresses from service - using OS facilities provides a number of advantages as it both avoids code duplication (and potential bugs) in the daemon, and eliminates an entire potential attack surface as undesired connections never have a chance to interact with any of the daemon code.

**Comment by partim** [comment]
@ebais Would @wk’s suggestion to use OS facilities for connection filtering work for you?

**Comment by job** [comment]
I'd suggest that this is handled at the OS level, like most daemons.

`routinator` just needs to make sure that whenever it listens on a network port, it only listens on `127.0.0.1` *unless* configured to do otherwise.

**Comment by partim** [comment]
Since 0.4, it won’t listen on anything by default anymore – everything needs to be explicitly configured.

I will close the ticket now. Feel free to re-open if there is any more discussion needed.
