### ISSUE TITLE
should ignore garbage in tal-dir

### ISSUE THREAD

**Issue by rfc1036** [NLnetLabs/routinator#117]
Files like backups found in the tal-dir should be ignored. This should be easy enough to implement in load_tals(). Two approaches are common:

- whitelist: only read *.tal and ignore everything else
- blacklist: read everything but files matching e.g. /(~|\.dpkg-[a-z]+)$/ and /^\./

**Comment by CameronNemo** [comment]
Whitelist `*.tal` please.

**Comment by rfc1036** [comment]
Whitelisting is what is actually documented in routinator(1), but I cannot find that code in load_tals().

**Comment by partim** [comment]
Oops. I shall fix the code.
