### ISSUE TITLE
Quickstart docs are wrong

### ISSUE THREAD

**Issue by devicenull** [NLnetLabs/routinator#141]
Quickstart says to do this, although the command doesn't exist:

<pre>
# routinator init
error: Found argument 'init' which wasn't expected, or isn't valid in this context

USAGE:
    routinator [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try --help
</pre>

**Comment by devicenull** [comment]
Ahhh... those docs are for current HEAD, not 0.3.3

**Comment by wk** [comment]
Indeed, this is not a bug - if you access the documentation under the [v0.3.3](https://github.com/NLnetLabs/routinator/tree/v0.3.3) tag, it makes no mention of the 'init' keyword which does not yet exist there.
