### ISSUE TITLE
/json?filter-prefix produces invalid JSON

### ISSUE THREAD

**Issue by devicenull** [NLnetLabs/routinator#143]
The result of a call to the '/json?filter-prefix=108.61.0.0/16' endpoint produces this output:

<pre>
{
  "roas": [
,
    { "asn": "AS20473", "prefix": "108.61.0.0/16", "maxLength": 24, "ta": "arin" }
  ]
}
</pre>

Which is not actually valid JSON (extra comma).  This was with 25d8554c

'/json?filter-asn=AS20473' has the same issue
<pre>
{
  "roas": [
,
    { "asn": "AS20473", "prefix": "2604:ab80::/32", "maxLength": 48, "ta": "arin" },
    { "asn": "AS20473", "prefix": "2a0c:da01::/48", "maxLength": 48, "ta": "ripe" },
    { "asn": "AS20473", "prefix": "2001:df3:ba00::/48", "maxLength": 48, "ta": "apnic" },
    .....
</pre>

**Comment by partim** [comment]
Oops. I probably shouldn’t have tested with CSV only. Thanks for reporting!
