### ISSUE TITLE
filter-asn seems like it should accept a raw ASN

### ISSUE THREAD

**Issue by devicenull** [NLnetLabs/routinator#144]
Is there a reason I have to put this in as 'AS20473' instead of just 20473?
<pre>
# routinator vrps --filter-asn 20473
Invalid ASN "20473" in --filter-asn
</pre>

At the very least, that error message is fairly confusing as to what the problem is

**Comment by netravnen** [comment]
> At the very least, that error message is fairly confusing as to what the problem is

Indeed.

Editing the error message to make it clear to the user in what format
the $asn-value is expected to be inputted in. Could be a simple massive
improvement.

**Comment by netravnen** [comment]
> Is there a reason I have to put this in as 'AS20473' instead of just 20473?

Talk about coincidence.

Got included with an upcoming [commit to the docs][0].

[0]:
https://github.com/NLnetLabs/rpki-doc/pull/7/files#diff-c94e23e401e175ee7c399c97d3eff1c7R138

**Comment by AlexanderBand** [comment]
@partim and I briefly discussed what the notation should be and I suggested to keep the "AS" prefix, to keep it consistent with the VRP output like you see it in the CSV:
```
ASN,IP Prefix,Max Length,Trust Anchor
AS12735,95.70.187.0/24,24,ripe
```
Clearer error message aside, I'm fine with whatever though and can update the docs accordingly.

**Comment by partim** [comment]
There’s no harm in accepting both ways, so I’ll implement that.
