### ISSUE TITLE
Document minimum requirement for systemd file

### ISSUE THREAD

**Issue by momorientes** [NLnetLabs/routinator#152]
The provided systemd unit file only works for systemd >= [240](https://github.com/systemd/systemd/blob/09e5c07fbd23d098edf2e0b51fbf402f07474dae/NEWS#L5)  which implements `Type=exec`.
Therefore a packaged routinator won't work on Ubuntu 18.04 LTS.

**Comment by partim** [comment]
Looks like we can provide several ‘variants’ for `cargo deb`. So perhaps we can take the systemd unit file out of the default variant and then add two version with a minimal and advanced unit file, respectively.

**Comment by momorientes** [comment]
that sounds like an even better solution!

**Comment by momorientes** [comment]
I was just approached on IRC how I resolved this issue.  
My hotfix was to create an override for systemd, by creating `/etc/systemd/system/routinator.service.d/overrides.conf`:
```
[Service]
Type=simple
SystemCallFilter=
```

However fixing this with a special variant for `cargo deb` sounds like the best solution to me.

**Comment by partim** [comment]
Two observations from playing with systemd today: While it complains about the exec type, it also happily replaces it with simple and moves on. Second, if you leave `SystemCallFilter` empty, it blocks _all_ system calls and Routinator will be killed the first time it wants memory. So you really need to leave it out altogether.
