### ISSUE TITLE
Prefix Prometheus metrics with `routinator_`.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#157]

**Comment by partim** [comment]
This is going to be a breaking change, so this is for 0.5.

**Comment by AlexanderBand** [comment]
As per https://phabricator.wikimedia.org/T225108#5237480, via @XioNoX

**Comment by wk** [comment]
This would also be consistent with the prometheus [best practices](https://prometheus.io/docs/practices/naming/) guide.

**Comment by partim** [comment]
Fixed by #162.
