### ISSUE TITLE
HTTP requests longer then 1024 bytes are rejected

### ISSUE THREAD

**Issue by devicenull** [NLnetLabs/routinator#158]
This one was fun to troubleshoot:
<pre>
curl http://127.0.0.1:3334/metrics -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'accept-encoding: gzip, deflate, br'  -H 'cookie: _ga=GA1.2.1917824926.1541712818; __cfduid=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; ajs_group_id=null; ajs_user_id=%22aaaaaaaaaaaaaaaaaaaaaaaayr%22; ajs_anonymous_id=%22a0000000000000000000000000%22; __mmapiwsid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; __idcontext=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; __lc.visitor_id.aaaaaaa=aaaaaaaaaaa.aaaaaaaaaa; lc_sso1253281=1234567890123'</pre>

I was seeing failures hitting the HTTP with my web browser, but only on our production server.  It turns out my browser was sending a bunch of cookies, which was pushing the request size past 1024 bytes, which caused failures per https://github.com/NLnetLabs/routinator/blob/master/src/http.rs#L152

This also gives a very generic 'Internal Server Error' message, which was not obvious what was wrong

**Comment by wk** [comment]
In light of #142 and this, it might be a sufficiently early opportunity to reconsider how trivial the HTTP listener is going to be over time (and what environments it will be called from), and perhaps switch from the homebrew implementation toward [hyper](https://github.com/hyperium/hyper) or even [reqwest](https://github.com/seanmonstar/reqwest).

**Comment by partim** [comment]
For the record #142 would have happened with Hyper, too.

Given that HTTP seems to slowly turn into a primary component of Routinator rather then being just a monitoring interface, it might indeed by better to switch to Hyper.
