### ISSUE TITLE
make JSON output form compatible with RIPE Validator

### ISSUE THREAD

**Issue by job** [NLnetLabs/routinator#16]
Arouteserver (and other software) relies on having the TAL name per entry in the JSON format, this is used for granular filtering on what ROAs to use and which not to use.

```
ARouteServer 2018-11-04 03:41:43,420 WARNING Invalid ROA: {u'prefix': u'91.231.153.0/24', u'asn': u'AS21485', u'maxLength': 24}, missing trust anchor
```
If the intention is that Routinator can be used as a drop-in replacement for RIPE NCC's validator, please make the JSON format compatible:

```
{
  "roas" : [ {
    "asn" : "AS0",
    "prefix" : "202.13.72.0/24",
    "maxLength" : 24,
    "ta" : "APNIC RPKI Root"
  }, {
    "asn" : "AS0",
    "prefix" : "203.147.108.0/31",
    "maxLength" : 31,
    "ta" : "APNIC RPKI Root"
  }, 
   ....
```

**Comment by partim** [comment]
Thanks for the report!

A quick fix could be to add a field with a value of "N/A" or somesuch to the JSON. Would that be helpful in the short run?

For the next version, we’ll add proper support. However, as we are using RFC 7760 TAL format, there is no name available. We could use the file name, the file name without the extension `.tal` or even the Subject Name of the root certificate, although the latter is confusingly different between RIRs so maybe that is not the best choice.

**Comment by job** [comment]
I’m less interested in the quick fix approach.

However, I am fine with the TAL filename without “.tal”! Thanks!
