### ISSUE TITLE
Prometheus # TYPE for some metrics wrong

### ISSUE THREAD

**Issue by momorientes** [NLnetLabs/routinator#160]
The following metrics show `# TYPE gauge` instead of `# TYPE <metric_name> gauge` .
```
last_update_start
last_update_duration
last_update_done
serial
```

I will provide a PR for this.

**Comment by qybl** [comment]
FYI #161 actually fixed #154. #156 did not :)

**Comment by partim** [comment]
Might be a version thing. #156 made my Prometheus installation go green again.

**Comment by qybl** [comment]
Hum, I tried with a current master and `cargo build` and `cargo build --release`. Prometheus was 2.10.0 fresh from prometheus.io. Only after I pulled again with #161 merged did prometheus stop erroring out on routinators /metrics.
As I'm new to building rust software might have been some error on my side, I don't know.

**Comment by partim** [comment]
Nono, this is my laziness. I was testing with Prometheus 1.5.2 (which seems to be the version that Debian Stretch has). Should have also tested with latest Prometheus.
