### ISSUE TITLE
tracking back to a bad repository

### ISSUE THREAD

**Issue by morrowc** [NLnetLabs/routinator#168]
Routinator reports this:
# routinator update 
rsync://59e6c66f3466/rpki: failed with status exit code: 10
rsync://59e6c66f3466/rpki: rsync: getaddrinfo: 59e6c66f3466 873: Name or service not known
rsync://59e6c66f3466/rpki: rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

(this is also syslog'ed)

I see this in the repositories directory:
root@routinator:~/.rpki-cache/repository# ls
59e6c66f3466  repository.lacnic.net  rpki.apnic.net  rpkica.twnic.tw  rpki-repository.nic.ad.jp
ca.rg.net     rpki.afrinic.net	     rpki.arin.net   rpki.cnnic.cn    rpki.ripe.net

there's nothing really useful in that number/letter named directory ... how do I track back to where this came from? :)

I presume something like:
  some tal had a list of downstream CAs ... one is this knucklehead

but :) maybe more logged data or something in the docs would make this a bit more discoverable? :) Also 'is this important?' would be good to know!

**Comment by AlexanderBand** [comment]
I saw this for the first time on the 27th of June. The structure `rsync://59e6c66f3466/rpki` fits with LACNIC, the others use different paths in their repos.

**Comment by morrowc** [comment]
ok .. since 'this is just a test' :)

rm -rf 59*
and routinator  update

and...
root@routinator:~/.rpki-cache/repository# rm -rf 59e6c66f3466/
root@routinator:~/.rpki-cache/repository# routinator update
root@routinator:~/.rpki-cache/repository# routinator vrps -p 192.187.27.0/24
ASN,IP Prefix,Max Length,Trust Anchor
AS53831,192.187.26.0/23,24,arin
AS396982,192.187.26.0/23,23,arin

ok.. some transient wonkiness from lacnic?
Maybe there's a step here:
  "clean up after a repository disappears"

that's not happening in the code?

**Comment by partim** [comment]
Not yet, no. There’s #50, though.

**Comment by morrowc** [comment]
Oh.. then :) consider this a +1 for that issue I guess.
