### ISSUE TITLE
Retry if failed rsync

### ISSUE THREAD

**Issue by XioNoX** [NLnetLabs/routinator#185]
For unknown reason (unrelated to Routinator), one rsync run failed on one of our validators, issue that I couldn't reproduce and triggered our monitoring. The next run, 1h later, cleared the issue.
It might be useful to have an automatic retry shortly after with some back-off mechanism to not hammer the rsync server if it's having a real issue.

**Comment by partim** [comment]
We are going to redesign the entire re-validation timing strategy as part of the RRDP implementation. (There’s already a couple of tickets around that).

In the meantime, I would suggest to set the `--refresh` time to something like 300 seconds. We should probably change the default to that, too.

**Comment by AlexanderBand** [comment]
Almost every operator I talk to nowadays uses a refresh time between 300 and 900 seconds.

**Comment by partim** [comment]
We have now lowered the default refresh time to 600 seconds. Do you think this solves the issue or would you prefer to have a separate configurable timeout for this case?

**Comment by XioNoX** [comment]
600s solved the issue for us, we don't have the need for a separate timeout anymore.
Thanks!
