### ISSUE TITLE
routinator validate - high CPU

### ISSUE THREAD

**Issue by naytsons** [NLnetLabs/routinator#189]
Using the validate command via the CLI takes about 10 seconds to respond and CPU spikes to 99%.  However, validating via HTTP responds instantly with no CPU spike.  Is the CLI behaviour expected?

**Comment by partim** [comment]
When you run `validate` via the command line, Routinator will first update the local cache. This takes some time. When you use the HTTP interface, the cache is updated regularly in the background.

If you run the command line `validate` with the `-n` (or `--noupdate`) option, Routinator will not update the local cache and assume it is updated. This is useful if you do use `validate` a lot – just remember to occasionally run without the `-n` or run `routinator update`.

I will add a note to the man page with this suggestion.
