### ISSUE TITLE
Docker build fails because of OpenSSL.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#194]

**Comment by partim** [comment]
This fails because there is no OpenSSL library for the musl target on the Debian build image. I think this would have to be built manually.

@wk, is there a reason this builds atop a Debian image and not Alpine directly?

**Comment by wk** [comment]
Utilizing the rust-lang docker base image allowed for convenient control of rust version, those images happento be based on top of Debian.

Addressed in #199 (from work done in #198 by @partim) to move build over completely to alpine and meet openssl dependency.

**Comment by partim** [comment]
Additionally, we don’t even need OpenSSL anymore.
