### ISSUE TITLE
routinator needs a minimal man page and some improved error codes

### ISSUE THREAD

**Issue by Jakker** [NLnetLabs/routinator#2]
The man page need some description of the "cache" structure so one doesn't run into thongs as below.
[script.txt](https://github.com/NLnetLabs/routinator/files/2244867/script.txt)

**Comment by partim** [comment]
Initial man page added via PR #3.

I’ll add some better formatting for `io::Error` next.

**Comment by partim** [comment]
Better reporting for `ProcessingError` is in the `rpki-rtr` branch.
