### ISSUE TITLE
Key doesn't match TAL until restart

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/routinator#211]
With Routinator 0.5.1 (Docker) running create a new TAL file in the tals/ directory.
After the refresh period expires Routinator detects the new TAL file but complains in the logs:
```
https://some.fqdn/ta/ta.cer: key doesn't match TAL.
```
Yet after `docker restart routinator` the TAL file is accepted.
```
Found valid trust anchor https://some.fqdn/ta/ta.cer. Processing.
```

**Comment by partim** [comment]
Routinator does _not_ reload the TALs between validation runs. This is on purpose as it increases robustness in normal operation.

Issue #200 requests implementation of a reload via signals.

**Comment by ximon18** [comment]
Should the error message perhaps be different then, e.g. "Ignoring new TAL 'xxx', please restart to load it." ?

**Comment by partim** [comment]
It doesn’t even look at the directory ever again, so that would require extra code and whatnot.
