### ISSUE TITLE
feature request: allow specifying source IP for outbound requests

### ISSUE THREAD

**Issue by appliedprivacy** [NLnetLabs/routinator#226]
In some environments the default way to determine the outbound source IP address will fail
because the link networks are not announced in BGP.

For such setups it would be beneficial to explicitly specify the source IP address that is used when initiating connections (ie. repo fetches).

**Comment by partim** [comment]
This is already available:

For rsync, you have to convince rsync to do that. You can define arguments to rsync via Routinator’s config-file-only option `rsync-args`. I think `--address` is the rsync option you want there.

So, something like:

```text
rsync-args = ["--address", "127.0.0.1"]
```

should work.

For RRDP (so, from 0.6.1 onwards), `--rrdp-local-addr` (also available as the config option `rrdp-local-addr`) allows you to specify the local address.

**Comment by partim** [comment]
Did this solve your problem?

**Comment by appliedprivacy** [comment]
Yes thank you.

https://www.nlnetlabs.nl/pipermail/rpki/2019-September/000083.html
