### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by tasoss** [NLnetLabs/routinator#233]
Hello.
I would like to ask if it's normal to have such load
 16:08:26 up 20:21,  1 user,  load average: 6.74, 4.29, 3.79
Java is the process that uses most cpu.
The OS is CentOS Linux release 7.7.1908 (Core)
The machine has 8 cores!
Any ideas?

**Comment by partim** [comment]
This is probably a bit of a simplification, but with 8 cores, a load of up to 8 is fine. During validation Routinator will currently use five threads so it may briefly raise the load to 5 all by its own. This shouldn’t last long though.

Note that Routinator does not use or invoke anything Java.

**Comment by tasoss** [comment]
Thanks for answering.
Well  the cpu load is contantly like this.
Now about java...i have to do my research because i haven't installed the two specific machines.
Let me see what is going on with java and let you know please.

**Comment by tasoss** [comment]
The problem is not related to routinator.
Sorry!
