### ISSUE TITLE
Missing TAL Behaviour Clarification

### ISSUE THREAD

**Issue by benmaddison** [NLnetLabs/routinator#24]
The manpage states:
> Unfortunately, the terms and conditions of
  the North American registry ARIN do not allow us to include  their  TAL
  with  the  Routinator.  We instead include a crippled version that will
  cause Routinator to refuse to work and print instructions on how to get
  the TAL instead.

The observed behaviour is consistent with the above. However, we currently plan to enable SOV *without* relying on the ARIN TAL (because of issues with the RPA), and the docs are silent on how to do this correctly.

It appears that `routinator` will start correctly if the placeholder `arin.tal` file is removed beforehand.
Please clarify:
1. Is this the expected behaviour?
2. Is this the correct/supported way to run without one of the RIR TALs?
3. Is this behaviour to remain consistent in future releases?

If yes to all, then a documentation update is in order.

**Comment by partim** [comment]
Yes to all. I refrained from mentioning this in fear that people would just go for the path of least resistance and just delete the arin.tal.

But you are right, this should probably be stated.

**Comment by partim** [comment]
I’m closing the ticket – don’t hesitate to reopen if you disagree with my solution!

**Comment by benmaddison** [comment]
Thanks @partim, lgtm
