### ISSUE TITLE
Routinator reports ca.rg.net has an unusable cert, despite having valid LetsEncrypt

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#264]
The certificate of ca.rg.net was recently [fixed](https://twitter.com/enoclue/status/1209933106720829440?s=21), but running `routinator -v vrps` still reports:
```
RRDP https://ca.rg.net/rrdp/notify.xml: Updating server
https://ca.rg.net/rrdp/notify.xml: https://ca.rg.net/rrdp/notify.xml: error trying to connect: invalid certificate: UnknownIssuer
Marking RRPD server 'https://ca.rg.net/rrdp/notify.xml' as unusable
```

However, `curl https://ca.rg.net/rrdp/notify.xml` works fine, as do browsers.

<img width="848" alt="Screenshot 2019-12-26 at 13 46 29" src="https://user-images.githubusercontent.com/3448859/71476757-faafad80-27e6-11ea-9524-e1a099f414f4.png">

**Comment by lukastribus** [comment]
https://twitter.com/LukasTribus/status/1210194833933000705

> Intermediate certificate is still missing, so it only works for User-Agents that happen to have that intermediate cert in the cache already https://ssllabs.com/ssltest/analyze.html?d=ca.rg.net

**Comment by randyqx** [comment]
well, i have hacked a bit.  `https://www.ssllabs.com/ssltest/analyze.html?d=ca.rg.net` says `A+`.  but i am not sure i believe it, as it also says `A+` for http sites with the intermediate missing; e.g. `https://psg.com/`.  i suspect that part of the issue is alex is using a different validation path than browsers, curl, or even other rrdp.

**Comment by AlexanderBand** [comment]
Your hacking solved the issue @randyqx. Now that there's an intermediate cert Routinator is happy.

```
RRDP https://ca.rg.net/rrdp/notify.xml: Updating server
Serials: us 3230, them 3230
RRDP https://ca.rg.net/rrdp/notify.xml: Delta update succeeded.
```

Thanks!
