### ISSUE TITLE
Routinator doesn’t check the manifest hash of a CRL

### ISSUE THREAD

**Issue by job** [NLnetLabs/routinator#265]
https://lists.nlnetlabs.nl/pipermail/rpki/2019-December/000109.html

**Comment by job** [comment]
heya, could I ask for an update on this one? it is blocking me from using routinator in NTT's production network

**Comment by partim** [comment]
Given that this needs some rewiring, I want to make this part of some major reconstructing work starting in March.

**Comment by job** [comment]
Ok! Thank you
