### ISSUE TITLE
Filter out invalid repositories

### ISSUE THREAD

**Issue by XioNoX** [NLnetLabs/routinator#267]
A bit similar to #22 

Routinator sometimes tries to rsync from invalid repositories:
`rsync://localhost/repo/`
`rsync://some.domain/repo/`

See for example: https://grafana.wikimedia.org/d/UwUa77GZk/rpki?orgId=1&from=now-30d&to=now&fullscreen&panelId=51

This triggers our monitoring, but it's not actionable (or relevant) to us. Maybe it should ignore them (or return a different error code) until it at least synced them successfully once?

**Comment by partim** [comment]
This is implemented in #113.

I have limited the filtering of actual host names to just ‘localhost’ for now. Trying to filter stuff that could be a legit domain name is a can of worms I don’t want to open, given the new TLD program where basically anything can be a TLD. We could do configurable filter lists, but they may be outdated and cause hard to debug issues.

In addition to ‘localhost,’ the PR also filters IP addresses and anything that contains an explicit port. The latter could be debatable, but I think that shouldn’t really be happening in public rsync URIs.
