### ISSUE TITLE
Expired CRLs should trigger invalidation of all underlaying objects

### ISSUE THREAD

**Issue by job** [NLnetLabs/routinator#274]
It appears that the routinator doesn't consider an expired CRL cause to consider underlaying objects invalid.

Related to https://github.com/NLnetLabs/routinator/issues/265

**Comment by AlexanderBand** [comment]
Thank you for your report. This will also be considered in the efforts scheduled for March.

**Comment by timbru** [comment]
Actually the standards are unclear about this, and worse they leave this as a choice to the implementor. I believe that most implementations treat stale CRLs much like stale MFTs - meaning that they are often accepted, at least until the manifest EE certificate is expired.

The behaviour regarding CRLs is not specified for RPKI (one would expect something in RFC 6487, but no..) - the behaviour for MFTs is full of 'local policy' text (see section 6 of RFC 6484).

It would be better if we could agree on one sane way to deal with this in the IETF - users expect that all validators behave similarly - in contrast to what the standards say.

**Comment by job** [comment]
Upon further reflection i think is a critical security issue

**Comment by AlexanderBand** [comment]
Discussion on this topic is continuing on [the sidrops mailing list](https://mailarchive.ietf.org/arch/msg/sidrops/tCybZO7YvXbdVm5pA7DbHEnuKEc/).

**Comment by partim** [comment]
Routinator now has a command line (and config file) option `--stale` that let’s you chose how to deal with stale objects. The default is still at the old ‘warn but proceed’ setting so as to not surprise current users during upgrades.
