### ISSUE TITLE
Use RRDP exclusively to update local RPKI repository

### ISSUE THREAD

**Issue by gkeller2** [NLnetLabs/routinator#276]
I was playing around with _routinator_ and noticed that there's no way to force it to update the local repository using RRDP exclusively. Does the option exist and I missed it?

**Comment by gkeller2** [comment]
This is probably not the right forum to ask how to use the tool. I'll reach out to the mailing list. Sorry.

**Comment by partim** [comment]
Nono, this is absolutely the right place!

I believe `--disable-rsync` does what you want to do?
