### ISSUE TITLE
Make Docker Hub ‘latest’ refer to the last release

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#295]
Currently, ‘latest’ refers to the head of the master branch which means it is less tested than it should be. Build some magic to make it refer to the last released version instead.

**Comment by partim** [comment]
@ximon18 kindly fixed Docker Hub so that latest is now whatever latest release tag was pushed.

**Comment by ximon18** [comment]
After discussion with @partim we have changed the Docker Hub content and autobuild rules such that the new normal is:

- On push to GitHub master, Docker Hub will be automatically triggered to clone the GitHub `master`  branch sources and build and tag a Docker Hub image as `nlnetlabs/routinator:unstable` - _**this is new behaviour.**_
- On push of a new GitHub tag of the form `vX.Y.Z`, Docker Hub will be automatically triggered to clone the GitHub `vX.Y.Z` tagged sources and:
  - Build and tag a Docker Hub image as `nlnetlabs/routinator:vX.Y.Z` - this is the same behaviour as before.
  - Build and tag a Docker Hub image as `nlnetlabs/routinator:latest` - _**this is different behaviour than before.**_
