### ISSUE TITLE
Feature request: webinterface like rpki-validator-3

### ISSUE THREAD

**Issue by schadom** [NLnetLabs/routinator#314]
Hello, i love the stability and easiness of routinator as RP and RTR-server, but i also like the GUI of ripencc's rpki-validator-3 very much. By chance, do you have any plans for adding a similiar webinterface to routinator as well? Thanks

**Comment by partim** [comment]
We don’t have any plans. This isn’t because we are opposed to the idea but rather we are a little uncertain what use cases people have for using the UI.

Could you perhaps outline which parts of the RIPE NCC Validator’s UI you are using and would like to see offered by Routinator?

**Comment by nielsdenotter** [comment]
Not knowing the reason for 'shadom' for this feature I would like to mention our usecase for this request and that is editting the 'exceptions.json'. It's much easier for 1st/2nd line to whitelist prefixes from GUI perspective than editting a json file. If this could be added, that would be really great.

**Comment by partim** [comment]
The one thing I would kind of like to avoid is the web interface actually changing configuration or state of a running Routinator because that suddenly means we need to supply some kind of protection against tempering with it.

Things like a HTML/JS frontend for the validity check should totally be doable.

**Comment by nielsdenotter** [comment]
> changing configuration or state of a running Routinator

Does that include 'editting' the whitelist to you? That would the most import reason to have one for us. I agree that the webinterface must then not be left open to anyone (nginx with authorization in front). Could it be a configuration option which is off by default? Or will this make the interface part too complicated.

**Comment by partim** [comment]
I’m tempted to do a SLURM editor as a separate, stand-alone thing. The extra effort to then set it up would serve as a bit of protection against someone just setting an option and opening themselves up for trouble. It’ll also keep Routinator smaller, which is probably a good thing.

**Comment by ngoburdhan** [comment]
We often have requests from people that are learning RPKI to "check their work..".  The "Preview" feature in the NCC's validator is generally where I point them to...

**Comment by partim** [comment]
Routinator 0.8.3 now includes a UI for checking the validity of prefixes. I’ll close this issue.

If you feel there are features missing from the UI, please either reopen or create a new issue.
