### ISSUE TITLE
Improve logging for bad certificate errors

### ISSUE THREAD

**Issue by devicenull** [NLnetLabs/routinator#318]
My 0.6.4 install reports this error every few minutes:

> routinator[15520]: Sending fatal alert BadCertificate

From an operations standpoint this isn't really a great error message.  What was routinator doing when it encountered this invalid certificate?  Where did it send this fatal alert to?

**Comment by partim** [comment]
You are absolutely right, this is quite terrible. By way of explaining, this error is logged directly by the the TLS library, so an RRDP server presented a certificate that wasn’t acceptable for some reason.

I shall look into filtering out these direct log messages and produce better ones.
