### ISSUE TITLE
Support for optional keep-alive in TCP transport

### ISSUE THREAD

**Issue by sanjmonkey** [NLnetLabs/routinator#320]
It would be great to have some functionality to optionally add support for a keep-alive to be sent in TCP, at a configurable interval.  

The use case being; somewhere in the path between RTR and router there is something tracking TCP sessions, and it sometimes kills them because its timers are not readily configurable and has a timeout interval < RTR refresh_interval.  RTR alone often isn't chatty enough to keep sessions alive.  I've seen this recently when routinator is a kubernetes pod and IPVS TCP timeouts default to 900s, whilst RFC8210 recommends a default of 3600s for refresh interval.

RFC8210 encourages the keep-alive behaviour;
```
   "To reduce exposure to dropped but non-terminated sessions, both
   caches and routers SHOULD enable keep-alives when available in the
   chosen transport protocol.”
```

In testing this behaviour with routers, I've implemented a stream proxy in NGINX and told it to set `so_keepalive` on the RTR listener socket.  In testing, both Arista and IOS-XR respond to the TCP keep-alive as expected, and this is enough to keep IPVS from eating the sessions, and maintaining recommended RTR refresh interval of 3600s.

**Comment by partim** [comment]
That seems like a good idea, indeed. We will add this to 0.8.0 at the latest.

Note that by default, Routinator has a refresh interval of ten minutes. It advertises the time until it expects the next refresh to finish as the RTR refresh interval. That may be unnecessarily often. But then, a serial update without any changes is only a quick exchange of a couple of bytes.

**Comment by partim** [comment]
Keepalives were removed when upgrading to Tokio 1.0 and have not yet been brought back.
