### ISSUE TITLE
grafana integration - quesion

### ISSUE THREAD

**Issue by dudster83** [NLnetLabs/routinator#324]
not an issue, but a stupid question, I guess
I'd install everything, seems better than other validators.
I'm still having troubles on the grafana integration
I can see the results under <ip:9556>/metrics with curl or regular browsing.
when i'm trying to add Prometheus data source and point it to the server, i can't fetch the data
what am I missing please?

**Comment by ximon18** [comment]
## SSH into the Prometheus server

1.To add the metric source you must edit the `prometheus.yml` file adding a stanza under `scrape_configs` like this:
```
scrape_configs:
   ...
   - job_name: 'routinator'
    static_configs:
    - targets: ['domain.name.of.your.routinator.instance:9556']
```
`/metrics` is the default so we don't need to specify that.
2. Reload Prometheus, e.g. `sudo systemctl reload prometheus.service`.

## In the Prometheus web user interface

3. On the targets page, e.g. http://domain.name.of.your.prometheus.instance:9090/targets, you should see your new job and its status. It will show as state unknown at first and change to state UP.

![image](https://user-images.githubusercontent.com/3304436/81011472-56a2d680-8e58-11ea-9f0c-638740309e8a.png)

4. On the graph page, e.g.
http://domain.name.of.your.prometheus.instance:9090/graph, you should be able to query for a Routinator metric, e.g. http://domain.name.of.your.prometheus.instance:9090/graph?g0.range_input=15m&g0.stacked=1&g0.expr=routinator_rrdp_status&g0.tab=0

![image](https://user-images.githubusercontent.com/3304436/81011618-8c47bf80-8e58-11ea-87aa-aabea19d8dc2.png)

## In the Grafana web user interface:

5. You need to have added your Prometheus instance as a datasource. Press the settings cog on the left in the web ui, click on Data Sources -> Add data source -> Prometheus and set HTTP URL to http://domain.name.of.your.prometheus.instance:9090/.
6. Click + on the left in the web ui, click on Import and enter 11922 in the "Grafana.com Dashboard" field and press "Load".

Dadda! You now hava a Routinator dashboard in Grafana.

![image](https://user-images.githubusercontent.com/3304436/81011753-c31dd580-8e58-11ea-9f74-e67f62871ae7.png)

See:
- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config

Hope that helps,

Ximon

**Comment by dudster83** [comment]
Hi Ximon
thanks for your fast and detailed reply, of course it helped.

**Comment by ximon18** [comment]
Great, glad that worked!

For anyone reading this in future the guidance above was correct at the time for the following application versions:
- Routinator v0.6.4
- Prometheus 2.9.2
- Grafana 6.7.1.
