### ISSUE TITLE
Would be nice to have ARIN OT&E TAL

### ISSUE THREAD

**Issue by eosborne-vio** [NLnetLabs/routinator#363]
It would be handy to have the ARIN OT&E TAL included in tals/
https://www.arin.net/reference/tools/testing/#trust-anchor-locator-tal

**Comment by partim** [comment]
We could add the option to install the testbed TALs for the RTRs via dedicated options to the `init` command.

I am a bit worried that people might accidentally keep them in their production system, but I guess that also can happen when files are copied manually into the TAL directory.

**Comment by Daned27** [comment]
I was also looking to see whether there was a way to add the ARIN OTE TAL

**Comment by eosborne-vio** [comment]
It's probably more work, but an argument to the routinator cli, maybe
`--test` to tell it to load all test_* TALs, would also get you the guard
rails you want.

**Comment by partim** [comment]
My assumption was that most people only want the test TAL for a single RIR. But I guess having `--all-test-tals` should not be too bad, either.

I’m now also thinking that maybe providing a `tal` subcommand for TAL management might be useful: You could list the present TALS and perhaps clean them up in some way.

**Comment by AlexanderBand** [comment]
For reference: [RIPE NCC testbed TAL](https://www.ripe.net/manage-ips-and-asns/resource-management/rpki/rpki-test-environment) and [APNIC testbed TAL](https://rpki-testbed.apnic.net)
