### ISSUE TITLE
how to set/revise the ip address and port of the configuration file

### ISSUE THREAD

**Issue by JC-ZI** [NLnetLabs/routinator#364]
Dear Supports,
I am new. 
(1) May You provide me the full step manual for CentOS 7? 
https://rpki.readthedocs.io/en/latest/routinator/installation-notes.html#statically-linked-routinator
May I just follow up the steps of SELinux using CentOS 7 for the installation routinator on CentOS 7?
Coz, can't get ROA files normally after the installation.

(2) May I know how to set/revise the ip address and port of the configuration file? 

Thanks a lot.

Isaac

**Comment by partim** [comment]
I believe the SELinux steps should indeed also work with non-SELinux Centos 7. It might be possible to skip some steps. Sadly, we don’t really use Centos around here. So if you you get stuck, it might be worth trying the [RPKI mailing list](https://lists.nlnetlabs.nl/mailman/listinfo/rpki).

For your second question, there’s two servers included with Routinator: RTR and HTTP. The former is set via the `rtr-listen` config file option, the latter via `http-listen`.

All options are explained in the manual page which you can access via `routinator man`.
