### ISSUE TITLE
Drop user privileges even if not detached.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#368]
Currently, the `user` and `group` options are only honoured when detaching from the terminal. If Routinator is run in server mode, it should always dropping privileges (and probably do all the other stuff) when not detaching.

**Comment by ximon18** [comment]
Also update the DEB packaging to take advantage of this fix. The relevant comment from #360 was:

> 2. For the package to run routinator as the correct user on older platforms (Ubuntu 16.04, Ubuntu 18.04, Debian 9) the minimal service file has been updated to include `User=routinator`, meaning it is not as minimal as it was. We could add a third service file to avoid altering the minimal one that we have today. _Note: I do NOT use the Routinator `user` and `group` configuration options to drop privileges from user root as they have no effect if `--detach` is not also used, but when using `--detach` the systemd unit no longer works (it just shows the program as exited when started), perhaps it would with further configuration (e.g. `Type=forking`, specifying the pid file, etc), perhaps systemd doesn't expect the program to fork itself and just sees the parent process exit (at least I think that's what I saw in my testing)?._
