### ISSUE TITLE
failure scenarios and it's impact on RTR

### ISSUE THREAD

**Issue by lukastribus** [NLnetLabs/routinator#379]
Hello,

I'm currently evaluating RPKI RP's and have a few questions.

I'm concerned about bugs, misconfigurations or other issues (in all RP/RTR setups) that will cause VRP's on the production routers to become stale, because I believe this is the worst-case in RPKI ROV deployments.

I worry about how:

- crash bugs in the validation code
- hangs during RPKI validation (even in rsync), that block the entire validation
- memory allocation failures (like failed malloc)
- Linux OOM-killer (killing the process with the largest amount of memory usage)
- admin mistakes

impact the RTR service:

The best-case scenario in my mind is that the RTR server goes down completely and all RTR sessions die, so that the production routers are aware there is a problem with that RTR end point and stop using it (failing over to other RTR servers, if available).

How would routinator behave in those situations? Is the RTR server running within the same process, so a crash would bring down RTR sessions and routers converge? Or does the RTR part keep running when the validator crashes, and distribute stale VRP's ?

I'm also thinking about monitoring:

- for periodic successful validation runs (thinking about how to trigger an ALIVE signal to something like [healthchecks.io](https://healthchecks.io/docs/http_api/) )
- validation run time (like [healthchecks.io run time measurement](https://healthchecks.io/docs/measuring_script_run_time/) )

Considering that we will probably start with something more simple than prometheus, I'd guess we can just call the prometheus exporter function and extract the data out of there.

Any opinions about this would be very much appreciated.

**Comment by partim** [comment]
Routinator’s RTR and HTTP servers indeed run in the same process, so they will die if the whole process dies for any reason. Rust has a concept called ‘panics’ that happen in unexpected situation such as out-of-memory but also when unexpected states are encountered (sort of like an always-on assert in C). Normally, in multi-threaded programs just the affected thread will disappear, but you can switch to abort on any panic. We should probably enable that given that we really don’t have any recovery strategy.

For the monitoring, just using either the /metrics or the /status endpoints is perhaps the easiest approach. They both will give you last validation start, end, and duration.

RTR version 1 also has a facility to signal to clients how long they should continue to use the data after the RTR server went away. We currently set this to a static number that can be configured via the expire option – it defaults to two hours. I was thinking to perhaps be a bit smarter about it and consider when data goes stale or expires, but that may need some discussion first.

**Comment by partim** [comment]
I split off the abort issue to #382.

**Comment by partim** [comment]
Given that it has been quiet, I am closing the issue. If your questions have not been answered, feel free to reopen!
