### ISSUE TITLE
SLURM filtering diagnostics

### ISSUE THREAD

**Issue by momorientes** [NLnetLabs/routinator#380]
I couldn't find any metrics endpoint or log message regarding the status of the exceptions currently active.  
In our scenario we have a hand full of routinator instances running globally and it would be great if we could somehow monitor  if and when they implemented the exceptions we specified.

Cloudflares gortr for instance logs the following message:
`gortr_1     | time="2020-09-21T07:00:53Z" level=info msg="Slurm filtering: 180178 kept, 1 removed, 0 asserted"`
on every reevaluation.

I would suggest to add 2 gauge metrics representing a count of `prefixFilters` and `prefixAssertions`, e.g.:
```
routinator_slurm_prefix_filters 0
routinator_slurm_local_assertions 0
```

**Comment by partim** [comment]
The one for filtered VRPs will appear as part of the new filtering logic introduced in #377.

We don’t yet have a metric for added VRPs in that PR nor are these things logged. I will add those before merging the PR.
