### ISSUE TITLE
Routinator returns an incorrect RPKI Validation status

### ISSUE THREAD

**Issue by vamseedhar-reddyvari** [NLnetLabs/routinator#414]
Hi,

We are using the routinator (0.8.0-rc3) to check RPKI Validation status of routes and stumbled upon this route which we believe is INVALID but the routinator is saying VALID. 

```
Prefix: 218.188.106.0/24
ASN: 9304
```
The output pasted below shows that the "/24" prefix is matched by a "/32" VRP. We tried the same route with "/25" and all the way to "/31" and all returned VALID with the "/32" as a matching VRP.
```
{
  "validated_route": {
    "route": {
      "origin_asn": "AS9304",
      "prefix": "218.188.106.0/24"
    },
    "validity": {
      "state": "valid",
      "description": "At least one VRP Matches the Route Prefix",
      "VRPs": {
        "matched": [
          {
            "asn": "AS9304",
            "prefix": "218.188.106.0/32",
            "max_length": "32"
          }

        ],
        "unmatched_as": [
        ],
        "unmatched_length": [
          {
            "asn": "AS9304",
            "prefix": "218.188.104.0/22",
            "max_length": "22"
          }

        ]      }
    }
  }
}
```

**Comment by morrowc** [comment]
Poking around a little and taking out my 'what is rust?' goggles.. aaron from cogent and I propose:
  https://github.com/NLnetLabs/routinator/pull/415

hopefully that works out?

**Comment by morrowc** [comment]
Sorry, I also added a test for the functionality. (ipv4 test)

**Comment by partim** [comment]
Thanks for reporting! That is quite wrong, indeed.

And also thanks for the proposed fix!
