### ISSUE TITLE
Config option "rtr-tcp-keepalive" expects string, should be integer

### ISSUE THREAD

**Issue by johannesmoos** [NLnetLabs/routinator#418]
Routinator should accept the config (passed on command line with ```-c|--config```) that is displayed by ```routinator config```

Currently this is not the case. How to reproduce:

```
$ routinator config > routinator.conf
$ routinator -c routinator.conf       
Error in config file /opt/routinator/conf/routinator.conf: 'rtr-tcp-keepalive' expected to be a string.
```

Output from ```routinator config``` (problematic key/value only): ```rtr-tcp-keepalive = 60```
Setting ```rtr-tcp-keepalive = "60"``` in config file does work, however ```rtr-tcp-keepalive = 60``` should be accepted

**Comment by partim** [comment]
Argl. We need to add more tests to config handling. This keeps breaking in new and creative ways.
