### ISSUE TITLE
routinator v0.8.0 failed to install on RHEL 8.1

### ISSUE THREAD

**Issue by bravenh** [NLnetLabs/routinator#421]
I am trying to install routinator v0.8.0, but hit the following:

     Running `rustc --edition=2018 --crate-name bytes /home/routinator/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.6/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=c7cb2bf58ce7f4ff -C extra-filename=-c7cb2bf58ce7f4ff --out-dir /tmp/cargo-installN1Uev9/release/deps -L dependency=/tmp/cargo-installN1Uev9/release/deps --cap-lints allow`
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /home/routinator/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.6/src/bytes.rs:132:18
    |
132 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: failed to compile `routinator v0.8.0`, intermediate artifacts can be found at `/tmp/cargo-installN1Uev9`

Caused by:
  Could not compile `bytes`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name bytes /home/routinator/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.6/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=c7cb2bf58ce7f4ff -C extra-filename=-c7cb2bf58ce7f4ff --out-dir /tmp/cargo-installN1Uev9/release/deps -L dependency=/tmp/cargo-installN1Uev9/release/deps --cap-lints allow` (exit code: 1)
[routinator@ankv-lnx-010 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.1 (Ootpa)

How can I overcome this?

**Comment by partim** [comment]
This looks like you have a rather old version of Rust. This should work since Rust 1.39. Routinator requires at least 1.42. I’m not too familiar with RHEL, but it looks like 8.1 has Rust 1.31 only?

If there isn’t a way to get a newer version via official channels, you can give installing current Rust via `rustup` a try as explained e.g. here: https://www.rust-lang.org/tools/install

**Comment by partim** [comment]
Given that it has been quiet, I am closing the issue. Please reopen if you have further questions on the matter!
