### ISSUE TITLE
To Install Routinator v0.8.0 on CentOS

### ISSUE THREAD

**Issue by JC-ZI** [NLnetLabs/routinator#422]
Dear Support,

I'm a new and we are using CentOS. May I know if we should follow the links' steps to set up Routinator v0.8.0?
https://rpki.readthedocs.io/en/latest/routinator/installation-notes.html#selinux-using-centos-7
Is there any support update for CentOS 7 / CentOS 8?

**Comment by partim** [comment]
Procedures shouldn’t have changed 0.8.0 compared to those installation notes. I _think_ the notes should also work with CentOS 8, but we don’t actually use CentOS, so I can’t be really sure.

If you encounter any issues, I would suggest you write to the [RPKI mailing list](https://lists.nlnetlabs.nl/mailman/listinfo/rpki) as it is more likely that someone there has installed Routinator on CentOS.
