### ISSUE TITLE
0.8.0 prefixfilters in slurm files not working

### ISSUE THREAD

**Issue by cwiech** [NLnetLabs/routinator#423]
I could be missing something, but it looks like version 0.8.0 has a problem with prefixfilter entries in the slurm file. Comparing with version routinator/0.7.1 , using a slurm it will filters the matches as expected (database.out.csv came from the api /csv... and the Prefix status commands are pulling from the API as well).  Picking a random route/asn on a lab system:

{"slurmVersion":1,"validationOutputFilters":{"prefixFilters":[{"asn":13335,"comment":"none"}],"bgpsecFilters":[]},"locallyAdd
edAssertions":{"prefixAssertions":[],"bgpsecAssertions":[]}}

```
 grep "1\.1\.1\.0" database.out.csv

Prefix status: 1.0.0.0/24, AS13335 not-found
Prefix status: 1.1.1.1/24, AS13335 not-found

```
In version: routinator/0.8.0 , the routes don't seem to get filtered using the same slurm file, the original entries are still in the database.

```

grep "1\.1\.1\.0" database.out.csv
AS13335,1.1.1.0/24,24,apnic

Prefix status: 1.0.0.0/24, AS13335 valid
Prefix status: 1.1.1.1/24, AS13335 valid
```

Whitelist seem to work fine

{"slurmVersion":1,"validationOutputFilters":{"prefixFilters":[{"asn":13335,"prefix":"1.1.1.0/24","comment":"none"}],"bgpsecFi
lters":[]},"locallyAddedAssertions":{"prefixAssertions":[{"asn":1337,"prefix":"80.80.80.0/24","maxPrefixLength":24,"comment":
"none"}],"bgpsecAssertions":[]}}

```
grep "80\.80\.80\.0" database.out.csv 
AS1337,80.80.80.0/24,24,N/A

Prefix status: 80.80.80.0/24, AS1337 valid
```

**Comment by partim** [comment]
Sadly, it looks like you didn’t miss something and the filters really aren’t applied.

I will commit a fix today and start the process of releasing version 0.8.1.
