### ISSUE TITLE
Allow file input and output for prefix validation 

### ISSUE THREAD

**Issue by barryhe** [NLnetLabs/routinator#430]
We were trying to increase the interval between consecutive refreshes (--refresh) to a large value for testing purposes. It seems there is an upper bound to the length of intervals: the interval will always be around 1.5 hours even if the value of the flag is way larger than 1.5 hours (we used 86400 seconds in our experiments). I monitored the interval length by checking the timestamps in /status.

**Comment by partim** [comment]
The refresh value is only the upper bound of the refresh time. If objects in the repository expire before that time, a new validation run will start earlier.

**Comment by barryhe** [comment]
Thanks for replying! So there's no way to prevent a validation from happening? We are exploring options of holding the next validation until a certain amount of time. I guess "--expire" will not do the work as well as I tried large values (172800) and it doesn't make any difference.

**Comment by partim** [comment]
> So there's no way to prevent a validation from happening?

Not currently, I am afraid. The intention here was to not serve expired objects.

May I ask what your reason for wanting to delay validation runs is?

> I guess "--expire" will not do the work as well [...]

No, this is currently only used in the timer values sent to RTR clients.

**Comment by barryhe** [comment]
We have some pipelines to download VRPs periodically through Routinator, and we want to build a routine test to make sure our origin validator works the same as the Routinator given the same set of VRPs. Therefore, we do not really want the Routinator to refresh -- otherwise the validation outputs may be slightly different as Routinator can have a newer set of VRPs. We want to increase the interval between refreshes so that we can decrease the chance of hitting validations.

Just in case you are curious - theoretically we will experience content changes as long as the interval is not infinity, but if the interval is large enough and we time it well it should be rare to see diffs in outputs.

**Comment by partim** [comment]
If you are okay with using Routinator from the command line instead of the HTTP service, you could use a combination of the `update` command together with `vrps` or `validate` using the `--noupdate` option. This way, you could run `update` periodically to update the cache and then stick to that cache via `--noupdate`. However, make sure that `update` doesn’t overlap with other runs as the cache may be inconsistent during an update run.

**Comment by barryhe** [comment]
Got it, thanks for the idea! However, we may expect to validate a lot of prefixes (> 1 million) in a test, and running commands is just a bit to slow for us...

I am also wondering if it's possible to add a --noupdate flag to the HTTP server. Is it very difficult to do something like this?

**Comment by partim** [comment]
It would certainly be doable but I am a bit hesitant to have a server that doesn’t update.

How about adding an option to the `validate` command to read the input from a file and produce a file? Would that help you?

**Comment by barryhe** [comment]
Yes, validation through a file will definitely help! Do you want me to submit another feature request or we can just stick with this issue?

**Comment by partim** [comment]
Keeping this one is fine. I’ll just rename it.
