### ISSUE TITLE
TLS support for the HTTP listener

### ISSUE THREAD

**Issue by appliedprivacy** [NLnetLabs/routinator#442]
To avoid having to run an additional webserver on the routinator host to get transport layer security (TLS) via a reverse proxy like nginx, it would be great if routinator itself had support for HTTPS like for example node_exporter.

**Comment by partim** [comment]
We will add TLS to RTR in the next (major) release, anyway, so adding it to HTTP should be easy enough.

As a disclaimer: there won’t be ACME support nor will there be rate limiting and such, so at least public-facing Routinators should probably still be kept behind a reverse proxy.
