### ISSUE TITLE
API endpoint to look up certificate for prefix

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator#446]
As a repository operator, in some situations, I want to look up a certificate based on a prefix or AS number. As a user, I can image doing the same when validating a geofeeds file with the proposed signatures. Ideally I could look this up using an API endpoint (possibly even: through a web UI).

The prefix can be more-specific than what is on the certificate. The AS number can be one out of a range that is on the certificate. Because of this, it can not easily be emulated with a combination of grep and a one-liner like
```bash
find . \
  -name \*.cer \
  -exec sh -c 'openssl x509 -in $1 -noout -text -inform DER > $1.txt' x {} \;
```

This may be a nich use case but I could not find it in the issue tracker.

**Comment by partim** [comment]
I am a bit torn on this. On the one hand, the foundations for this are actually present – there is code now for doing validation runs for other things than just ROV – but we obviously don’t keep track of certificate prefixes at all. So, doing this as a command line command that invokes a validation run to get to the information is relatively easy.

As an API/UI it would require keeping track of additional data (I don’t think doing validation runs triggered by remote APIs is a good idea). It certainly can be done but it’s extra code that hardly anyone uses. Maybe [JDR](https://github.com/NLnetLabs/JDR-web) would be better suited to that?

**Comment by ties** [comment]
I agree that keeping data in memory for a niche use case is likely not worth it. As well as triggering validation runs remotely (easy denial of service vector). I can look up the same data using JDR, but getting a view of the currently valid data is harder.

For me the advantage of an API would be that the "time of check, time of use" gap when checking if a CA exists would be reduced. But I have a workaround for my use case. Let's shelve this for now.
