### ISSUE TITLE
routinator ui not found

### ISSUE THREAD

**Issue by alez1983sa** [NLnetLabs/routinator#457]
hi i've installed routinator with deb package and also with cargo
when i try to get webgui i retreive not found message

api, and monitoring is ok

where i do mistake?

**Comment by AlexanderBand** [comment]
Routinator 0.8.3 is currently a [release candidate](https://lists.nlnetlabs.nl/pipermail/rpki/2021-January/000260.html). This means you have to explicitly install it by running `cargo install -f --version 0.8.3-rc1 routinator`. Binary packages for Debian and Ubuntu are available via the -proposed 'distributions.'

If running `routinator --version` returns "Routinator 0.8.3-rc1", the UI is available via the regular HTTP interface at the `/`
endpoint.

**Comment by alez1983sa** [comment]
Hi,
My running version is 0.8.2

As I understand in this version gui is not present

It means that all works fine

Thks

Regards Alessandro
_______________________________

[1585391229581]
Alessandro Romano
Network Engineer

LIBRA SRL

Sede Legale
Via Ferdinando I D'Aragona, 87
81028 Santa Maria a Vico CE Italia

Sede Operativa
Via Casilina Km 191.300
81050 Pastorano CE Italia

P.IVA IT 03811260615
Email: alessandro.romano@libradsl.it<mailto:alessandro.romano@libradsl.it>
Mobile: (+39) 3351402534
_______________________________

Da: Alex Band <notifications@github.com>
Inviato: domenica 31 gennaio 2021 12:13
A: NLnetLabs/routinator <routinator@noreply.github.com>
Cc: Alessandro Romano <alessandro.romano@libradsl.it>; Author <author@noreply.github.com>
Oggetto: Re: [NLnetLabs/routinator] routinator ui not found (#457)


Routinator 0.8.3 is currently a release candidate<https://lists.nlnetlabs.nl/pipermail/rpki/2021-January/000260.html>. This means you have to explicitly install it by running cargo install -f --version 0.8.3-rc1 routinator. Binary packages for Debian and Ubuntu are available via the -proposed 'distributions.'

If running routinator --version returns "Routinator 0.8.3-rc1", the UI is available via the regular HTTP interface at the /
endpoint.

**Comment by AlexanderBand** [comment]
Hi Alessandro, most likely we will release the official version of 0.8.3 in the coming week.
