### ISSUE TITLE
Add concise info on Stale, Unsafe objects, RTR connections

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#465]
<img width="762" alt="Screenshot 2021-02-08 at 15 11 32" src="https://user-images.githubusercontent.com/3448859/107248929-1a2d8800-6a33-11eb-81df-0d428bc21a4b.png">

The UI shows counters for stale and unsafe objects, as well as locally added VRPs and RTR connections. These numbers could have links to show additional details.

**Comment by partim** [comment]
Additional information for stale, unsafe, and locally added VRPs was added in #493.

**Comment by partim** [comment]
Remainder fixed by #519.
