### ISSUE TITLE
GET parameters of validity API endpoint

### ISSUE THREAD

**Issue by BirkSchroederCBB** [NLnetLabs/routinator#466]
According to the documentation at https://rpki.readthedocs.io/en/latest/routinator/daemon.html#api-endpoints, the validity of a prefix can be verified via GET Requets:

`/validity?asn=as-number&prefix=prefix`

However it seems that routinator does not parse the url encoded prefix parameter correctly. The following does result in a http 400 Error:
`validity?asn=<asn>&prefix=<network>%2F<length>`

Without encoding it works:
`validity?asn=<asn>&prefix=<network>/<length>`

**Comment by partim** [comment]
Thanks for the report. We’ll add percent decoding for the query in the next version.

As an aside: Unless I am missing something, percent encoding is not necessary for the slash there. RFC 3986 even suggest not to do it.

**Comment by BirkSchroederCBB** [comment]
Thanks for the update.

In the python script that uses the api I use  a naive 
`r = requests.get("http://<host>/validity", params={"asn":<asn>, "prefix": "<prefix>"})`
to make the request. I do not know why the requests module applies the percent encoding.

**Comment by partim** [comment]
I agree that that should just work.
