### ISSUE TITLE
Feature Request: HTTP serve validation results with Last-Modified header field

### ISSUE THREAD

**Issue by reschke** [NLnetLabs/routinator#469]
I'm currently running tests with various validators, GETting JSON output and post-processing it. It would be very useful if the JSON output would be served with a Last-Modified header field, indicating the time when the last validation run finished.

(see also https://github.com/cloudflare/cfrpki/issues/83)

**Comment by partim** [comment]
That sounds like a good idea, indeed! We will try and implement it in 0.9.

We should also support If-Modified-Since and ETags.

**Comment by reschke** [comment]
...and If-None-Match, if you provide Etags...

**Comment by reschke** [comment]
Note: Rust newbie.

The code that serves the ROAs is easy to find. However, despite reading a lot, I couldn't quite figure out the "right" way to format a timestamp as an HTTP date. Is this functionality present in the libraries Routinator uses already?

**Comment by partim** [comment]
Yes, most date and time handling is done using the [chrono](https://crates.io/crates/chrono) crate. I believe [`DateTime::to_rfc2822`](https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#method.to_rfc2822) should provide the right format?

**Comment by reschke** [comment]
Unfortunately no; see <https://greenbytes.de/tech/webdav/rfc7231.html#preferred.date.format>. So it seems we'll need to come up with the correct format string for that...

**Comment by partim** [comment]
Shouldn’t be too difficult. However, I would prefer using an array of formatting items rather than a string since the latter needs to be parsed. We’re already using this strategy to generate the timestamp in the csvext format in [output.rs](https://github.com/NLnetLabs/routinator/blob/be8da401f18e50e3e351b24c1ce2c9010d9fed1a/src/output.rs#L412).

**Comment by reschke** [comment]
Ah, more pointers! Appreciated. I'll give it a try soonish.

**Comment by partim** [comment]
I’d like to keep the issue open for support of ETags, If-Modified-Since, and If-None-Match.

(Client-side suppor for ETags in RRDP is supposed to be added for 0.9 as well, so this can all be _ein aufwasch._)
