### ISSUE TITLE
Improve SLURM error reporting

### ISSUE THREAD

**Issue by netravnen** [NLnetLabs/routinator#48]
```
Dec 17 17:09:40 maggie routinator[23890]: Failed to load exceptions file /path/to/export_rfc8416_dn42.json: expected u32 for 'locallyAddedAssertions.prefixFilters.[].asn'
```
Am I wrong (doing incorrect formatting of [file][file]) or is the above a bug? _(I am not sure. As I am unsure of the restrictions or lack thereof concerning the `u32` type)_

The expections file I am trying to load with the `-x` option is [this export_rfc8416_dn42.json][file].

* What troubles me in particular. Is the error message (above) from `/var/etc/syslog` is incomprehensible. In the sense I am sorely missing a more in-depth explanation behind the error message. E.g. on what line first number number the error message concerns. _(hence this issue)_

[file]: https://raw.githubusercontent.com/netravnen/dn42-rpki-export.json-test/master/roa/export_rfc8416_dn42.json

**Comment by partim** [comment]
You are absolutely right, the error message isn’t particularly helpful.

What it is trying to tell you is that the "asn" fields are integers and thus the AS number mustn’t be enclosed in quotes.

We’ll look into better error reporting!

**Comment by netravnen** [comment]
Danke schön for the answer! :) Got it working now.

_Nb: A quick one could be to put a simple explanation in `test/slurm/README.md` about this error and/or things to remember when generating files to comply with SLUM standard._

**Comment by partim** [comment]
If you don’t mind, I’ll reopen the ticket as a more general ’Improve SLURM logging’ ticket.
