### ISSUE TITLE
DEB packages do not use `--locked` like other builds do

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/routinator#501]
The published installation instructions say to use `cargo install --locked` and the `Dockerile` also uses `cargo build --locked`. However, the DEB package built by `cargo deb` apparently doesn't use `--locked` as [its docs say](https://github.com/mmstick/cargo-deb#custom-build-flags):

> Flags after -- are passed to cargo build, so you can use options such as -Z, --frozen, and --locked. Please use that only for features that cargo-deb doesn't support natively.

And our `pky.yml` GitHub Actions workflow invokes cargo deb like so:

```
        if [[ "${VARIANT_NAME}" == "" ]]; then
          cargo deb --deb-version ${DEB_VER} -v
        else
          cargo deb --deb-version ${DEB_VER} --variant ${VARIANT_NAME} -v
        fi
```

**Comment by ximon18** [comment]
@partim: Should I submit a PR to pass `--locked` to `cargo deb` ?

**Comment by partim** [comment]
> Should I submit a PR to pass `--locked` to `cargo deb` ?

That would be nice, if you have the time.
