### ISSUE TITLE
Comments in JSON exception files generates error

### ISSUE THREAD

**Issue by netravnen** [NLnetLabs/routinator#52]
1. I recently tried to include comments at the top of a [JSON exception file][0] I load into routinator.
2. Routinator complains about the comments line prefixed with `//`.
3. Throws and error message. 
4. Refuses to start.

**Q:** Is valid JSON single line comments not acceptable in an exception file? _(or have I misunderstood an RFC somewhere? Read [the RFC][1] for the format of the exception file. But did not stumble over any obvious lines detailing if JSON comments is acceptable or not to include)_

[0]: https://github.com/netravnen/dn42-rpki-export.json-test/blob/870e4d04520962ae21c3a9264f43989659c4aae1/roa/export_rfc8416_dn42.json
[1]: https://tools.ietf.org/html/rfc8416

**Comment by partim** [comment]
I don’t think comments are allowed in JSON at all. The Internet seems to suggest to place your comment in an extra `"_comment"` field. Routinator ignores extraneous fields, so this should work.

**Comment by timbru** [comment]
There are ‘comments’ Json members for each of the filters and whitelists for this purpose, see here, and further: https://tools.ietf.org/html/rfc8416#section-3.3.1

The idea was that comments would be treated as first class data so that it can be parsed and possibly shown in an api or ui.

**Comment by netravnen** [comment]
@partim Hmm. Stumbled upon [Douglas Crockford 12.1.2012 G+ post][0] noting he removed comments from JSON. And [other post][1] noting no syntax exist for comments in JSON. Now I get why Routinator complains about it. (Even if lots of parsers still accept lines as comments if prefixed with `#`, `//` or enclosed in `/* */`.)

> The idea was that comments would be treated as first class data so that it can be parsed and possibly shown in an api or ui.

@timbru Will change my approach of how i include comments in my exception file. Thanks for the pointer! :)

[0]: https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr
[1]: https://raddevon.com/articles/json-comments/
