### ISSUE TITLE
Routinator won't compile on 32 bits machine

### ISSUE THREAD

**Issue by Jakker** [NLnetLabs/routinator#53]
If ones tries one will get the following error:

>    Compiling rpki v0.2.0
   Compiling routinator v0.2.0
error[E0425]: cannot find value `res` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.2.0/src/config.rs:1325:5
     |
1325 |     res > ::std::usize::MAX as i64
     |     ^^^ not found in this scope
> error: aborting due to previous error

As far as I understand at the code, it seems that the routinator cpmares a 32 bit counter (for elapsed seconds> to a 64 bit value.

**Comment by partim** [comment]
Thanks for reporting!

This has been fixed in master already. We'll do a 0.2.1 release soon.
