### ISSUE TITLE
Deprecate or keep `--unsafe-vrps`?

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#536]
The `unsafe-vrps` option has been in Routinator since 0.8.0, released in October 2020. What have we learned from this option? Do we want to keep it as is, change it or deprecate it?

**Comment by partim** [comment]
After some discussion on the Discord, the conclusion is to keep the feature, change the default value for the configuration variable to `accept` (i.e., don’t even log occurrences), and improve the wording of the log messages, including a link to a page in the manual explaining what this is all about.
