### ISSUE TITLE
v0.9.0-rc1 loads all TALS on start 

### ISSUE THREAD

**Issue by dsaunders06** [NLnetLabs/routinator#560]
as per usage init command should only load production TALS if no options provided 
"If none of --rir-tals, --rir-test-tals, or --tal is given, assumes --rir-tals."

with no options applied and starting 0.9.0-rc1 it appears all TALS are loaded 

valid-roas: 115075
valid-roas-per-tal: afrinic=1482 apnic-testbed=0 apnic=15035 arin-ote=31108 arin=35818 lacnic=7487 nlnetlabs-testbed=341 ripe-pilot=10 ripe=23794 
vrps: 299366
vrps-per-tal: afrinic=2191 apnic-testbed=0 apnic=71559 arin-ote=36881 arin=41702 lacnic=15161 nlnetlabs-testbed=5475 ripe-pilot=16 ripe=126381 
unsafe-vrps: 0
unsafe-filtered-vrps-per-tal: afrinic=0 apnic-testbed=0 apnic=0 arin-ote=0 arin=0 lacnic=0 nlnetlabs-testbed=0 ripe-pilot=0 ripe=0 
locally-filtered-vrps: 0
locally-filtered-vrps-per-tal: afrinic=0 apnic-testbed=0 apnic=0 arin-ote=0 arin=0 lacnic=0 nlnetlabs-testbed=0 ripe-pilot=0 ripe=0 
duplicate-vrps-per-tal: afrinic=33 apnic-testbed=0 apnic=195 arin-ote=6960 arin=36016 lacnic=1309 nlnetlabs-testbed=978 ripe-pilot=1 ripe=8 
locally-added-vrps: 0
final-vrps: 253866
final-vrps-per-tal: afrinic=2158 apnic-testbed=0 apnic=71364 arin-ote=29921 arin=5686 lacnic=13852 nlnetlabs-testbed=4497 ripe-pilot=15 ripe=126373

**Comment by partim** [comment]
Thank you for testing the release candidate!

I can’t reproduce the issue, though. If I run init without options, I get the RIR TALs only:

```
m@glaurung:~$ routinator -b /tmp/test init --accept-arin-rpa
Created local repository directory /tmp/test/repository
Installed 5 TALs in /tmp/test/tals
m@glaurung:~$ ls /tmp/test/tals/
afrinic.tal  apnic.tal  arin.tal  lacnic.tal  ripe.tal
```

Note that the command does _not_ delete any existing TALs in a directory, even if you provide the `--force` option. To start really fresh, you will have to delete the TAL directory or its contents first.

**Comment by dsaunders06** [comment]
Sorry I missed mentioning I’m doing this with the docker script to create a container. 

The hashed line around copying the Arim Tal if left hashed no TALs are copied but if unhashed it copies all TALs into the directory. 

I would have assumed all TALs need to be copied but only used based on INIT command

D'Wayne Saunders.

**Comment by partim** [comment]
Sorry for the late response – May is full of holidays here.

When started, Routinator reads all the files ending in .tal in the TAL directory and uses them as TALs. The `init` command simply places the requested TALs in the directory. It does, however, not delete unwanted TALs. This is also why you need to give it the `--force` option if the TAL directory already exists – the result may not be what you expect.

Which is to say, if you want to disable TALs, you currently have to delete them manually.

**Comment by dsaunders06** [comment]
Thanks for th info. I have worked around this by coping the specific TALS I require on container build. This has simplified things on my side and is more logical when reading the Code within the Dockerfile
