### ISSUE TITLE
UI Authentication

### ISSUE THREAD

**Issue by dudster83** [NLnetLabs/routinator#567]
Hello
Has anyone succeeded in installing Pam or any other radius module for nginx to achieve ui authentication with external radius?
I'm running routinator on ubuntu so if anyone can assist it would be great
David

**Comment by partim** [comment]
Sorry for the horribly late reply.

Routinator doesn’t have any special requirements, so this really is ‘normal’ Nginx configuration. I’m afraid we don’t have any experience with PAM and Nginx and can’t really help.
