### ISSUE TITLE
IPv4 and IPv6 ROA count

### ISSUE THREAD

**Issue by csdali13** [NLnetLabs/routinator#579]
Hi,

Could you please let me know is there a way we can get the IPv4 and IPv6 ROA count for the purpose of monitoring in Grafana? I could only find per tal number of ROAs (routinator_valid_roas) in the list of metrics available.

Thanks,
Dali

**Comment by partim** [comment]
We currently do not distinguish between IPv4 and IPv6 prefixes in the metrics. This could, of course, be added in one of the next versions, if desired.
