### ISSUE TITLE
Ensure the max-length isn’t smaller than the prefix lenght in SLURM files.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#584]
Currently, this is not checked _anywhere_ and may result in corrupt VRPs rejected by routers.

**Comment by partim** [comment]
While at it, double check that it can’t be longer than 32 or 128.

**Comment by ties** [comment]
Would it be good to also check this at the rtr level - since apparently
routers reject this?

**Comment by partim** [comment]
This should be an invariant of the VRP data type – it needs to be rejected during creation because once we are RTR stage, we don’t quite know what to do anymore.

**Comment by ties** [comment]
If that invariant holds all is fine as we :)
