### ISSUE TITLE
Make `/json` available under `/api/v1/json`

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#591]
For the API and front end work @density215 is doing, it would be more practical to have the data at the `/json` endpoint available under `/api/v1/json` (as well).

**Comment by density215** [comment]
hi, I'd even prefer having it like this:

`/json?select-prefix=<PREFIX>`

 will become

`/api/v1/prefix/<PREFIX>/select`

**Comment by density215** [comment]
On second thought (well, Alex's second thought): `/api/v1/vrp/<PREFIX>/select`

**Comment by partim** [comment]
Is there a need to have the `/select` at the end? Just `/api/v1/vrp/<PREFIX>` should be fine, no?

**Comment by partim** [comment]
I think we should discuss the best structuring for this, so I will delay the issue until 0.10.1.
