### ISSUE TITLE
Dumping stored data has incorrect structure

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#604]
Currently a `stored` directory is created with all RRDP publication points as a separate subfolder directly under it. 

- The parent folder should be called `store` instead
- All RRDP respositories should be in an `rrdp` subfolder (`rsync` does have its own subfolder).

<img width="414" alt="Screenshot 2021-07-19 at 15 57 15" src="https://user-images.githubusercontent.com/3448859/126171582-daabb24c-48c3-44d8-a055-26a05863146d.png">

**Comment by ties** [comment]
Could you split this up into subdirectories named after `h(hostname)[:2]` (or another way to uniformly distribute them over sub-folders)?

Since a repository operator can create an arbitrary number of sub-repositories I would be hesitant to store them all in one folder.

**Comment by partim** [comment]
That already happens. If there is a collision, a number is appended to the hostname. You need to consult `repositories.json` for the mapping between directory name and rpkiNotify URI.
