### ISSUE TITLE
Routinator Server replies to a Serial Query with a Malformed End of Data PDU. 

### ISSUE THREAD

**Issue by TonyDN09** [NLnetLabs/routinator#620]
When restarting after a reset sync and the client sends out a Serial Query, cache servers can respond with Cache Response or Cache Reset or Error Report PDU to a Serial Query (RFC8210). 
However, Routinator Server sends back a malformed EndOfData PDU of length 8. End of Data PDUs are of length 12 and 24 in version 0 and version 1 respectively. It causes the client to send a Corrupt Data PDU and mark the cache as disabled. The cache can only be synced after the retry interval. 
![Screen Shot 2021-07-21 at 11 48 22 AM](https://user-images.githubusercontent.com/87771464/126519232-4dc81e2c-7bdf-4b7c-bbd7-44ffa5a445a6.png)

**Comment by partim** [comment]
Thanks for the report!

I’m not entirely sure how that could have happened. Can you possibly make the full trace available?

Also, which Routinator version are you using?

**Comment by TonyDN09** [comment]
Hi,

Thanks for your reply. 

I am using Routinator 0.9.0. Looks like it happens after the routinator server stops and starts for a few times. I am using the server command with custom/local exception file, base directory and -rtr options. 

Do you have an email that I can share the .pcap file with?

**Comment by AlexanderBand** [comment]
Can you please send it to rpki-team@nlnetlabs.nl. Thanks!

**Comment by TonyDN09** [comment]
> Can you please send it to [rpki-team@nlnetlabs.nl](mailto:rpki-team@nlnetlabs.nl). Thanks!

An email with the trace has been sent to your email. Please keep me updated with the process. 
Thank you.

**Comment by partim** [comment]
Turns out the RTR code mistakenly used 7 as the PDU type for the Cache Reset PDU. A fix has been created as https://github.com/NLnetLabs/rpki-rs/pull/151. I will make a release of the rpki crate and this change will get into the final Routinator 0.10.0.

**Comment by TonyDN09** [comment]
Thank you.

**Comment by partim** [comment]
Thank you for the report! This issue is fixed starting in Routinator 0.10.0-rc2.
