### ISSUE TITLE
Simulate RPKI updates

### ISSUE THREAD

**Issue by ayalaalex** [NLnetLabs/routinator#623]
user@rpki:~$ routinator -x local_exp_total.json update
Failed to open store database at /home/user/.rpki-cache/repository/store: could not acquire lock on "/home/user/.rpki-cache/repository/store/db": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
Is there another Routinator running?

Fatal error. Exiting.

running 0.9.0-rc2

**Comment by partim** [comment]
This happens if there currently is another Routinator instance running. Do you perchance have a Routinator server running in the background?

On a side note: local exceptions are not considered by the `update` command as it only updates the local copy of the repository but doesn’t produce any output – which is when the local exceptions are applied.

**Comment by ayalaalex** [comment]
Thanks Martin,
I'm still learning how to use this tool. Just going with how other
colleagues were using it. I basically testing rpki and want to simulate
changes in the database.

So I first run with routinator -x localexp --rtr ip --http ip

then make changes to localexp file and run the update. Which is when I get
the exception that routinator is already running. Using older version
(0.7.1) works or the git master 0.10.0. But when I do it with 0.9.0 I get
error. What would be the way to simulate what I'm trying to do?

Alex

**Comment by ayalaalex** [comment]
So if I want routinator to send updates manually how would I accomplish this?

**Comment by partim** [comment]
Apologies, I somehow missed the question at the end of your response.

The local exceptions aren’t entered into the “database,” rather are considered every time Routinator produces a new data set. Thus, if you are running `routinator server` where this is done periodically, you can just change your files, wait for a new validation run to happen (you can set the time via the `--refresh` command) and then look at the output after. Alternatively, on the command line you can just run `routinator vrps` which does a single validation run and therefore uses the current local exceptions. The latter is probably better if you are testing your setup as it will error out before a validation run if your files are broken somehow. In the server, it will also not validate, but you will have to look at the logs to find that out.

**Comment by ayalaalex** [comment]
Ok so for example I'm trying to simulate RPKI server sending updates with announced and withdraw prefixes.  In the local file I put say 10 prefixes.  I see those 10 prefixes sent from RPKI server to my client.  I then make changes to the file, so add or remove prefixes and run routinator vrps, I don't need to use the -x or knows which file I used?  Sorry if I sound ignorant, I just want to be able to simulate the server sending updates to my client, and instead of waiting for changes to occur on one of the anchors I want to manually do it.

**Comment by partim** [comment]
You will always have to provide the SLURM file(s) to use via the -x argument.

What I meant was that if you run the `server` command, you don’t need to restart Routinator to pick up your changes to the file(s). It will re-read the files every time it does a validation run.

**Comment by ayalaalex** [comment]
Ok Gotcha thanks.
