### ISSUE TITLE
systemd-listen does not seem to work

### ISSUE THREAD

**Issue by Gunni** [NLnetLabs/routinator#639]
I was debugging today why my test XRv could not use the test routinator instance I was testing, the tcp connection gets accepted, sends a rtr reset query and then closes.

After quite a lot of debugging, and then finally trying to find the code that implements it, we couldn't find it.

It was only in config.rs... After a bit of git bisecting, it _seems_ like commit 2246085d9d81539cdcdcc97949f02e375bf1e48b (merge request https://github.com/NLnetLabs/routinator/pull/282) was refactoring a lot, and ... simply unimplemented the feature.

So since that commit, you have a regression, `systemd-listen = true` does nothing.

**Comment by partim** [comment]
Thanks for the report! That obviously shouldn’t have happened and will be fixed in the release after 0.10.0.
