### ISSUE TITLE
RTR over SSH

### ISSUE THREAD

**Issue by sarasalingam** [NLnetLabs/routinator#642]
I am interested to know the advantages and disadvantages of running RTR over SSH. There are some opinions, it does not protect anything apart from putting additional load on the router. I am interested to hear some view on this.

**Comment by AlexanderBand** [comment]
Hi @sarasalingam. Perhaps bringing up this topic on the RPKI Community [Discord server](https://discord.gg/8dvKB5Ykhy) or [mailing list ](https://lists.nlnetlabs.nl/mailman/listinfo/rpki) would get a discussion started.
