### ISSUE TITLE
Show which VRPs are added through SLURM

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#650]
Currently you can just see how many VRPs were added locally but I would like to see through an endpoint (and the UI) which ones.

**Comment by partim** [comment]
The jsonext output format contains that information. It’s a tad cumbersome, but it should work.

**Comment by AlexanderBand** [comment]
Admittedly the information is in the `jsonext` file, but digging through a 120MB file to find a couple of VRPs tagged with `"type": "exception"` may not be a super efficient way to do this.

**Comment by partim** [comment]
There’s tools for that ;)

Seriously, though: Routinator adds all VRPs listed as assertions in all SLURM files as they are, so I am not sure having a separate source for that is really all that useful. The value of the jsonext format is that you can see which of those were also in the real data. We _could_ provide that separately, but I am not sure there is enough value in it?
