### ISSUE TITLE
Crate tar 0.4.35 can create arbitrary directories due to links in the archive

### ISSUE THREAD

**Issue by alarig** [NLnetLabs/routinator#655]
Hello,

While making the ebuild for 0.10.1 I had this warning:
```
Error: Found 1 vulnerability:

Crate:    tar
Version:  0.4.35
Title:    Links in archive can create arbitrary directories
Date:     2021-07-19
ID:       RUSTSEC-2021-0080
URL:      https://rustsec.org/advisories/RUSTSEC-2021-0080
Solution: Upgrade to >=0.4.36
```

https://rustsec.org/advisories/RUSTSEC-2021-0080

**Comment by partim** [comment]
Thanks for the notification! The tar crate is used in the routinator-ui crate to download the JavaScript app and its assets during building. I have created an issue in the routinator-ui repository.
