### ISSUE TITLE
Not working: RPKI validator

### ISSUE THREAD

**Issue by chad-abizeid** [NLnetLabs/routinator#658]
https://rpki-validator.ripe.net/ui/

Origin ASN (optional)

If I leave it blank and only put in the prefix, it says "Please enter a valid ASN"

This has been ongoing for weeks, no fix.

**Comment by AlexanderBand** [comment]
Can you give an example prefix? Here is an example link that shows a prefix from the RIPE NCC:

https://rpki-validator.ripe.net/ui/193.0.0.0%2F21?validate-bgp=true&include=related_alloc,related_less_specific,related_more_specific

**Comment by chad-abizeid** [comment]
Even your link shows the same error. 

![Screenshot 2021-10-01 at 09-56-29 Routinator](https://user-images.githubusercontent.com/8635771/135632607-efa818f9-adb1-4c12-9dd0-f91b15fe0c81.png)

**Comment by AlexanderBand** [comment]
It seems that you don't have BGP and allocation data from the API. Can you have a look in your browser console if traffic to rest.bgp-api.net is being blocked? Alternatively, check:

http://rest.bgp-api.net/api/v1/prefix/193.0.0.0/21/search

**Comment by AlexanderBand** [comment]
You see it's loading for me:
<img width="1646" alt="Screenshot 2021-10-01 at 16 26 03" src="https://user-images.githubusercontent.com/3448859/135636822-48f1b55a-6c11-4b90-a452-1e35717b9c5f.png">

**Comment by chad-abizeid** [comment]
The joys of the internet. Forgot I installed NextDNS yesterday and that was the cause. Problem fixed by whitelisting rest.bgp-api.net, if anyone else has similar funky hiccup. 

Thanks for your help, sorry for the little oversight on my part.

**Comment by AlexanderBand** [comment]
No worries, glad it's resolved. Happy Routinating. 🚀
