### ISSUE TITLE
ASN lookup check?

### ISSUE THREAD

**Issue by hank-nuss** [NLnetLabs/routinator#661]
When doing a prefix check why isn't there an option to just provide the ASN and then display all found prefixes and their RPKI status?

Thanks,
Hank

**Comment by AlexanderBand** [comment]
Hi Hank, both the Routinator API and the BGP/RIR lookup API can do lookups by ASN, but combining these two and conveying the result in the user interface didn't make the cut for this release.

https://rest.bgp-api.net/api/v1/asn/3333,12654/search
https://rpki-validator.ripe.net/json?select-asn=3333
https://rpki-validator.ripe.net/api/v1/validity/3333/193.0.0.0/21

 It's on the roadmap though! https://github.com/NLnetLabs/routinator-ui/issues/39
