### ISSUE TITLE
Presence of `.DS_Store` on macOS causes rsync to fail

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#673]
I browsed around my repository directory using the macOS Finder. On the next validation run I got:
```
Fatal: failed to remove directory tree /Users/alex/.rpki-cache/repository/rsync/.DS_Store: Not a directory (os error 20)
Fatal error. Exiting.
```
This is macOS Monterey (12.1) on Apple Silicon.

**Comment by partim** [comment]
This happens because the rsync cleanup code assumes everything under `repository/rsync/` to be directories. We need a check for directories and just delete files.

**Comment by AlexanderBand** [comment]
In fact, it may have also left a hanging rsync process in its wake...
<img width="1052" alt="Screenshot 2022-01-06 at 14 59 40" src="https://user-images.githubusercontent.com/3448859/148394164-2ec0284a-d279-4997-99ed-74d3162537ec.png">
