### ISSUE TITLE
Failed to start Routinator 3000.

### ISSUE THREAD

**Issue by karunanithinsm** [NLnetLabs/routinator#680]
Hi Team,
 
when i ran systemctl status routinator, i got below error on RHEL8.4

 routinator --version
 Routinator 0.9.0
,
Above one is routinator version

systemctl status routinator
● routinator.service - Routinator 3000
   Loaded: loaded (/usr/lib/systemd/system/routinator.service; enabled; vendor preset: disabled)
   Active: failed (Result: core-dump) since Tue 2022-01-18 20:04:53 IST; 8s ago
     Docs: man:routinator(1)
  Process: 32044 ExecStart=/usr/bin/routinator --config=/etc/routinator/routinator.conf --syslog server (code=dumped, signal=ABRT)
 Main PID: 32044 (code=dumped, signal=ABRT)

Jan 18 20:04:53 routinator-r8 systemd[1]: routinator.service: Main process exited, code=dumped, status=6/ABRT
Jan 18 20:04:53 routinator-r8 systemd[1]: routinator.service: Failed with result 'core-dump'.
Jan 18 20:04:53 routinator-r8 systemd[1]: routinator.service: Service RestartSec=100ms expired, scheduling restart.
Jan 18 20:04:53 routinator-r8 systemd[1]: routinator.service: Scheduled restart job, restart counter is at 5.
Jan 18 20:04:53 routinator-r8 systemd[1]: Stopped Routinator 3000.
Jan 18 20:04:53 routinator-r8 systemd[1]: routinator.service: Start request repeated too quickly.
Jan 18 20:04:53 routinator-r8 systemd[1]: routinator.service: Failed with result 'core-dump'.
Jan 18 20:04:53 routinator-r8 systemd[1]: Failed to start Routinator 3000.

Some pls helpme out on this, i am new to this tool,.

TIA

**Comment by karunanithinsm** [comment]
Actually i have installed it on year back, at that time it was the latest one, don't know anything about this.
Tell me the command to get more logs, to share with you

**Comment by partim** [comment]
Does `journalctl -u routinator` show anything?

**Comment by karunanithinsm** [comment]
Starting Routinator 3000...
Jan 18 19:03:07 routinator-r8 systemd[1]: Started Routinator 3000.
Jan 18 19:03:07 routinator-r8 routinator[31450]: thread 'main' panicked at 'assertion failed: `(left == right)`
Jan 18 19:03:07 routinator-r8 routinator[31450]:   left: `5222665027584`,
Jan 18 19:03:07 routinator-r8 routinator[31450]:  right: `5105109172224`: insert_pid specified lsn 5222665027584 for pid 3107 in segment>
Jan 18 19:03:07 routinator-r8 routinator[31450]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jan 18 19:03:08 routinator-r8 systemd[1]: routinator.service: Main process exited, code=dumped, status=6/ABRT
Jan 18 19:03:08 routinator-r8 systemd[1]: routinator.service: Failed with result 'core-dump'.
Jan 18 19:03:08 routinator-r8 systemd[1]: routinator.service: Service RestartSec=100ms expired, scheduling restart.
Jan 18 19:03:08 routinator-r8 systemd[1]: routinator.service: Scheduled restart job, restart counter is at 5.
Jan 18 19:03:08 routinator-r8 systemd[1]: Stopped Routinator 3000.
Jan 18 19:03:08 routinator-r8 systemd[1]: routinator.service: Start request repeated too quickly.
Jan 18 19:03:08 routinator-r8 systemd[1]: routinator.service: Failed with result 'core-dump'.
Jan 18 19:03:08 routinator-r8 systemd[1]: Failed to start Routinator 3000.

**Comment by partim** [comment]
Can you also post your `/etc/routinator/routinator.conf` – or email it to rpki-team@nlnetlabs.nl if you don’t want to post it here?

**Comment by karunanithinsm** [comment]
Partim,
 routinator.conf fiel content has been  shared over mentioned mail, pls check

**Comment by partim** [comment]
Further research indicates that the error you are experiencing is happening in a library used only by the particular version of Routinator you are using. So, upgrading should indeed fix the issue. Alternatively, deleting the repository directory might also fix the issue in the short term.

**Comment by karunanithinsm** [comment]
How to delete the repository, pls share the  cmds

**Comment by partim** [comment]
Just delete everything in the directory listed as `repository-dir` in your Routinator config.

But let me re-iterate: You really should upgrade.

**Comment by karunanithinsm** [comment]
The server is in production , is there any service impact to resolve now, later will upgrade it to latest one

**Comment by partim** [comment]
Deleting the repository directory should not have any impact.

**Comment by karunanithinsm** [comment]
Can u pls provide  exact path and files need to be delete, i have already shared config file

**Comment by partim** [comment]
`sudo rm -rf /var/lib/routinator/rpki-cache/*` should do the trick.

**Comment by karunanithinsm** [comment]
Partim, you are fantastic, after hit above cmd, it's working fine in my Dev Environment, but in production it is not working

**Comment by partim** [comment]
What is the log output in production when it fails?

**Comment by karunanithinsm** [comment]
Hi Martin

As per your recommendation we are upgrading to 0.10.2 in production. We will let you know if we need any help post upgrade.

Thanks&Regards
NSM Karuna
8451098321


From: Martin Hoffmann ***@***.***>
Sent: 19 January 2022 16:52
To: NLnetLabs/routinator ***@***.***>
Cc: Karunanithi Nsm ***@***.***>; Author ***@***.***>
Subject: [External]Re: [NLnetLabs/routinator] Failed to start Routinator 3000. (Issue #680)


The e-mail below is from an external source. Please do not open attachments or click links from an unknown or suspicious origin.

What is the log output in production when it fails?

—
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=a370c422-fcebf8ae-a3714edd-ac1f6b00f158-a9c825ec6568271c&q=1&e=1f065fd8-5136-4202-b30e-fbc678af2103&u=https%3A%2F%2Fgithub.com%2FNLnetLabs%2Froutinator%2Fissues%2F680%23issuecomment-1016359687>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=c31a48b8-9c817434-c31bc247-ac1f6b00f158-850ac3f34bda26d2&q=1&e=1f065fd8-5136-4202-b30e-fbc678af2103&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXKVM72MBQ3PYX6S5NDIFATUW2NETANCNFSM5MHLTXCQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://protect2.fireeye.com/v1/url?k=53cd027b-0c563ef7-53cc8884-ac1f6b00f158-bdf0e841299e73a4&q=1&e=1f065fd8-5136-4202-b30e-fbc678af2103&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>
"Confidentiality Warning: This message and any attachments are intended only for the use of the intended recipient(s). 
are confidential and may be privileged. If you are not the intended recipient. you are hereby notified that any 
review. re-transmission. conversion to hard copy. copying. circulation or other use of this message and any attachments is 
strictly prohibited. If you are not the intended recipient. please notify the sender immediately by return email. 
and delete this message and any attachments from your system.

Virus Warning: Although the company has taken reasonable precautions to ensure no viruses are present in this email. 
The company cannot accept responsibility for any loss or damage arising from the use of this email or attachment."

**Comment by karunanithinsm** [comment]
Hi Martin

We have upgraded production routinator to 0.10.2.

The database is not getting synchronized. Can you refer the below logs


Can you help
Jan 20 17:50:04 routinator-r8 routinator[3856]: rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/2a246947-2d62-4a6c-ba05-87187f0099b2>
Jan 20 17:50:04 routinator-r8 routinator[3856]: CA for rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/2a246947-2d62-4a6c-ba05-87187>
Jan 20 17:50:04 routinator-r8 routinator[3856]:    AS394564
Jan 20 17:50:04 routinator-r8 routinator[3856]: rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/2a246947-2d62-4a6c-ba05-87187f0099b2>
Jan 20 17:50:04 routinator-r8 routinator[3856]: CA for rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/2a246947-2d62-4a6c-ba05-87187>
Jan 20 17:50:04 routinator-r8 routinator[3856]:    69.161.205.0/24
Jan 20 17:50:04 routinator-r8 routinator[3856]:    2620:e2:4000::/48
Jan 20 17:50:04 routinator-r8 routinator[3856]:    AS64230
Jan 20 17:50:04 routinator-r8 routinator[3856]: rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/521eb33f-9672-4cd9-acce-137227e971ac>
Jan 20 17:50:04 routinator-r8 routinator[3856]: CA for rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/521eb33f-9672-4cd9-acce-13722>
Jan 20 17:50:04 routinator-r8 routinator[3856]:    0.0.0.0/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    ::/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    AS0-AS4294967295
Jan 20 17:50:04 routinator-r8 routinator[3856]: rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/746e0111-fafb-430f-b778-d204cfcd99a8>
Jan 20 17:50:04 routinator-r8 routinator[3856]: CA for rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/746e0111-fafb-430f-b778-d204c>
Jan 20 17:50:04 routinator-r8 routinator[3856]:    0.0.0.0/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    ::/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    AS0-AS4294967295
Jan 20 17:50:04 routinator-r8 routinator[3856]: rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/76fe11d4-d352-4994-8f6c-d6c91b0b8415>
Jan 20 17:50:04 routinator-r8 routinator[3856]: CA for rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/76fe11d4-d352-4994-8f6c-d6c91>
Jan 20 17:50:04 routinator-r8 routinator[3856]:    0.0.0.0/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    ::/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    AS0-AS4294967295
Jan 20 17:50:04 routinator-r8 routinator[3856]: rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/f60c9f32-a87c-4339-a2f3-6299a3b02e29>
Jan 20 17:50:04 routinator-r8 routinator[3856]: CA for rsync://rpki.arin.net/repository/arin-rpki-ta/5e4a23ea-e80a-403e-b08c-2171da2157d3/f60c9f32-a87c-4339-a2f3-6299a>
Jan 20 17:50:04 routinator-r8 routinator[3856]:    0.0.0.0/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    ::/0
Jan 20 17:50:04 routinator-r8 routinator[3856]:    AS0-AS4294967295
Jan 20 17:50:21 routinator-r8 routinator[3856]: rsync://rpki.ripe.net/ta/: rsync: getaddrinfo: rpki.ripe.net 873: Name or service not known
Jan 20 17:50:21 routinator-r8 routinator[3856]: rsync://rpki.ripe.net/ta/: rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Jan 20 17:50:21 routinator-r8 routinator[3856]: No valid trust anchor for TAL ripe
Jan 20 17:50:21 routinator-r8 routinator[3856]: Fatal: failed to open directory /var/lib/routinator/rpki-cache/rrdp: No such file or directory (os error 2)
Jan 20 17:50:21 routinator-r8 systemd[1]: routinator.service: Succeeded.
Jan 20 17:51:45 routinator-r8 systemd[1]: Starting Routinator 3000...
Jan 20 17:51:45 routinator-r8 systemd[1]: Started Routinator 3000.
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://rpki.apnic.net/repository/: rsync: getaddrinfo: rpki.apnic.net 873: Name or service not known
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://rpki.apnic.net/repository/: rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Jan 20 17:52:05 routinator-r8 routinator[3903]: No valid trust anchor for TAL apnic
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://repository.lacnic.net/rpki/: rsync: getaddrinfo: repository.lacnic.net 873: Name or service not known
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://repository.lacnic.net/rpki/: rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Jan 20 17:52:05 routinator-r8 routinator[3903]: No valid trust anchor for TAL lacnic
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://rpki.afrinic.net/repository/: rsync: getaddrinfo: rpki.afrinic.net 873: Name or service not known
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://rpki.afrinic.net/repository/: rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Jan 20 17:52:05 routinator-r8 routinator[3903]: No valid trust anchor for TAL afrinic
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://rpki.arin.net/repository/: rsync: getaddrinfo: rpki.arin.net 873: Name or service not known
Jan 20 17:52:05 routinator-r8 routinator[3903]: rsync://rpki.arin.net/repository/: rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Jan 20 17:52:05 routinator-r8 routinator[3903]: No valid trust anchor for TAL arin
Jan 20 17:52:25 routinator-r8 routinator[3903]: rsync://rpki.ripe.net/ta/: rsync: getaddrinfo: rpki.ripe.net 873: Name or service not known
Jan 20 17:52:25 routinator-r8 routinator[3903]: rsync://rpki.ripe.net/ta/: rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
Jan 20 17:52:25 routinator-r8 routinator[3903]: No valid trust anchor for TAL ripe

From: Martin Hoffmann ***@***.***>
Sent: Wednesday, January 19, 2022 4:52 PM
To: NLnetLabs/routinator ***@***.***>
Cc: Karunanithi Nsm ***@***.***>; Author ***@***.***>
Subject: [External]Re: [NLnetLabs/routinator] Failed to start Routinator 3000. (Issue #680)


The e-mail below is from an external source. Please do not open attachments or click links from an unknown or suspicious origin.

What is the log output in production when it fails?

—
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=a370c422-fcebf8ae-a3714edd-ac1f6b00f158-a9c825ec6568271c&q=1&e=1f065fd8-5136-4202-b30e-fbc678af2103&u=https%3A%2F%2Fgithub.com%2FNLnetLabs%2Froutinator%2Fissues%2F680%23issuecomment-1016359687>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=c31a48b8-9c817434-c31bc247-ac1f6b00f158-850ac3f34bda26d2&q=1&e=1f065fd8-5136-4202-b30e-fbc678af2103&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXKVM72MBQ3PYX6S5NDIFATUW2NETANCNFSM5MHLTXCQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://protect2.fireeye.com/v1/url?k=53cd027b-0c563ef7-53cc8884-ac1f6b00f158-bdf0e841299e73a4&q=1&e=1f065fd8-5136-4202-b30e-fbc678af2103&u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>
"Confidentiality Warning: This message and any attachments are intended only for the use of the intended recipient(s). 
are confidential and may be privileged. If you are not the intended recipient. you are hereby notified that any 
review. re-transmission. conversion to hard copy. copying. circulation or other use of this message and any attachments is 
strictly prohibited. If you are not the intended recipient. please notify the sender immediately by return email. 
and delete this message and any attachments from your system.

Virus Warning: Although the company has taken reasonable precautions to ensure no viruses are present in this email. 
The company cannot accept responsibility for any loss or damage arising from the use of this email or attachment."

**Comment by partim** [comment]
There seem to be two issue:

*  `/var/lib/routinator/rpki-cache` doesn’t exist or isn’t writeable to the user running rountinator (fixable via `mkdir /var/lib/routinator/rpki-cache` followed by `chown -R routinator: /var/lib/routinator/rpki-cache` [replace `routinator` in the second command with the user you are actually running Routinator as if that differs]);
* the machine cannot resolve host names (that’s the `getaddrinfo: rpki.ripe.net 873: Name or service not known` you see all over the place). That may be a DNS issue or a networking issue.

**Comment by karunanithinsm** [comment]
Thank you so much for your kind help....Its working fine now
