### ISSUE TITLE
Determine the signed object type from the object itself, not its name.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#69]
Currently, we use the file ending to decide what kind of object we are dealing with. The more robust way would be to use the _eContentType_ field of the signed object.

**Comment by timbru** [comment]
You are right! But.. the extensions are defined in the RFCs. A ROA MUST use .roa, a certificate .cer etc. This was done specifically for implementations that have a hard time inspecting and then parsing/validating - signed objects are all similar, but CRLs and certificates are quite different. I think you can judge best how easy/hard this is to implement in routinator, and when to do it.

**Comment by partim** [comment]
Should have checked the RFC first. I seemed to remember the ending was a SHOULD. In this case, everything is fine (we check the correct content type when decoding an object).
