### ISSUE TITLE
Doing one-shot `vrps` validation runs sometimes leaves stray `rsync` processes

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#694]
I run Routinator interactively regularly. Every now and then this leaves a stray `rsync` process that I have to kill manually. I haven't checked in a few weeks, but I just killed four of them.

<img width="396" alt="Screenshot 2022-01-24 at 14 21 21" src="https://user-images.githubusercontent.com/3448859/150790975-052738eb-5433-4e8e-90e6-16b7ba2d1d47.png">

This is an M1 MacBook Pro.

**Comment by partim** [comment]
I believe this was fixed by #720 already.
