### ISSUE TITLE
Monitoring integration

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#7]
This is an issue to explore which monitoring products and platforms we might want to offer out-of-the-box integration for.

So far we have (in no particular order):
* [Prometheus](https://prometheus.io/)
* [Icinga](https://www.icinga.com/)
* [Metronome](https://github.com/juise/metronome)
* [Zabbix](https://www.zabbix.com/)
* [Nagios](https://www.nagios.org/)
* [Influxdb](https://www.influxdata.com/)
* SNMP, SMUX, AgentX

Feel free to add whatever it is you are using if it isn’t in the list already!

To elaborate a bit: we are planning to produce a set of metrics regarding both the Routinator’s health and the content of the RPKI cache it has and also provide some active service monitoring, probably based on an RTR client.

**Comment by bluikko** [comment]
I would second SNMP implemented as AgentX. AgentX is a newer interface, replacing SMUX, and is standardized in RFC 2741 and is in many ways better than SMUX.

**Comment by partim** [comment]
Given that the ticket was intended to be mostly exploratory, I’ll close it for now. We will evaluate adding SMTP support at some point, perhaps together with the other RPKI relying party software vendors.
