### ISSUE TITLE
Please support HEAD method on metric endpoint

### ISSUE THREAD

**Issue by micah** [NLnetLabs/routinator#704]
I'd like to run a lightweight prober against routinator's metrics endpoint, it would be fantastic if you would support the HEAD HTTP method

Routinator responds with a "405 Method Not Allowed" when you try to query the metrics endpoint using the HEAD HTTP method. If it simply returned a 200 instead, this would enable me to check that the end point is responding properly.

Why would you want to use a HEAD method?  It is useful for a health check to monitor the endpoint to ensure it is alive. You can do the same health check with the GET method, but then you need to download all the data that comes with the metrics, which is unnecessary (and a quick test here shows me that its 144k of data) and adds up when you are checking every 10 seconds or so.

Thanks for considering!

**Comment by partim** [comment]
Good timing! I am refactoring the HTTP server code right now anyway. Might as well include support for HEAD requests while I am at it.

**Comment by gthess** [comment]
Hi micah! I am not objecting to the idea (quite the opposite, why not?) but "probing against routinator's metrics endpoint" is what monitoring software is already doing when it fetches the metrics periodically. I am just wondering why you would need to check with HEAD manually.

**Comment by micah** [comment]
Mostly I need extra probes for redundancy/reliability purposes and without a healthz endpoint to check health, I would prefer to not send all that data over the wire to just check that its alive.

**Comment by partim** [comment]
As a quick win, you could switch to a `GET /version` which has a body of less than a dozen bytes.
