### ISSUE TITLE
error: could not compile `routinator-ui`

### ISSUE THREAD

**Issue by devops365** [NLnetLabs/routinator#724]
Hi there,

When executing an update via cargo it fails

This is a debian 10.11 and rust is latest
  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.59.0 (9d1b2106e 2022-02-23)

The error is : 

error: could not compile `routinator-ui`

Caused by:
  process didn't exit successfully: `rustc --crate-name routinator_ui --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-ui-0.3.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C metadata=4a71a71ec76a3fc2 -C extra-filename=-4a71a71ec76a3fc2 --out-dir /tmp/cargo-installtcDsUF/release/deps -L dependency=/tmp/cargo-installtcDsUF/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `routinator v0.10.2`, intermediate artifacts can be found at `/tmp/cargo-installtcDsUF`

Caused by:
  build failed

Thank you

**Comment by partim** [comment]
Hm, `(signal: 9, SIGKILL: kill)` looks rather suspicious.

Do you have some more output? If not, could you run cargo with `-v` and see if there is anything that would help with diagnosis?

**Comment by devops365** [comment]
Hello Partim and thank you for your prompt reply

Sure , here is the output with verbose on:



   Compiling routinator-ui v0.3.4
     Running `rustc --crate-name build_script_build --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-ui-0.3.4/build.rs --error-format=json --json=diagnostic-rendered-ansi,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off -C metadata=6ab0994b6b2b27b8 -C extra-filename=-6ab0994b6b2b27b8 --out-dir /tmp/cargo-installNE4aAn/release/build/routinator-ui-6ab0994b6b2b27b8 -L dependency=/tmp/cargo-installNE4aAn/release/deps --extern flate2=/tmp/cargo-installNE4aAn/release/deps/libflate2-2e1b2f6edd5d3fdc.rlib --extern reqwest=/tmp/cargo-installNE4aAn/release/deps/libreqwest-ab49c1f054bfd4a3.rlib --extern tar=/tmp/cargo-installNE4aAn/release/deps/libtar-2bac00c900b71eee.rlib --cap-lints allow -L native=/tmp/cargo-installNE4aAn/release/build/ring-a1088e8513c044b9/out`
     Running `/tmp/cargo-installNE4aAn/release/build/routinator-ui-6ab0994b6b2b27b8/build-script-build`
     Running `rustc --crate-name routinator_ui --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-ui-0.3.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C metadata=4a71a71ec76a3fc2 -C extra-filename=-4a71a71ec76a3fc2 --out-dir /tmp/cargo-installNE4aAn/release/deps -L dependency=/tmp/cargo-installNE4aAn/release/deps --cap-lints allow`
     Running `rustc --crate-name hyper_rustls --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.22.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C metadata=bd3e12189a0ce6f5 -C extra-filename=-bd3e12189a0ce6f5 --out-dir /tmp/cargo-installNE4aAn/release/deps -L dependency=/tmp/cargo-installNE4aAn/release/deps --extern futures_util=/tmp/cargo-installNE4aAn/release/deps/libfutures_util-6099575e8d3664dd.rmeta --extern hyper=/tmp/cargo-installNE4aAn/release/deps/libhyper-12e96715791fbefc.rlib --extern log=/tmp/cargo-installNE4aAn/release/deps/liblog-17dd83666760fff6.rmeta --extern rustls=/tmp/cargo-installNE4aAn/release/deps/librustls-f4493af0cac97b24.rmeta --extern tokio=/tmp/cargo-installNE4aAn/release/deps/libtokio-0ca69eb4de11e028.rmeta --extern tokio_rustls=/tmp/cargo-installNE4aAn/release/deps/libtokio_rustls-aa6360ee20838f20.rmeta --extern webpki=/tmp/cargo-installNE4aAn/release/deps/libwebpki-87455b1016383335.rmeta --cap-lints allow -L native=/tmp/cargo-installNE4aAn/release/build/ring-a3fe10e9f2fee5e2/out`
     Running `rustc --crate-name reqwest --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no --cfg 'feature="__rustls"' --cfg 'feature="__tls"' --cfg 'feature="blocking"' --cfg 'feature="hyper-rustls"' --cfg 'feature="rustls"' --cfg 'feature="rustls-tls"' --cfg 'feature="rustls-tls-webpki-roots"' --cfg 'feature="socks"' --cfg 'feature="tokio-rustls"' --cfg 'feature="tokio-socks"' --cfg 'feature="webpki-roots"' -C metadata=a03e6f84e74f6bfa -C extra-filename=-a03e6f84e74f6bfa --out-dir /tmp/cargo-installNE4aAn/release/deps -L dependency=/tmp/cargo-installNE4aAn/release/deps --extern base64=/tmp/cargo-installNE4aAn/release/deps/libbase64-fd5bc4ef0b84d29a.rmeta --extern bytes=/tmp/cargo-installNE4aAn/release/deps/libbytes-f43e2c916a06f602.rmeta --extern encoding_rs=/tmp/cargo-installNE4aAn/release/deps/libencoding_rs-4af3634cc3f61cf2.rmeta --extern futures_core=/tmp/cargo-installNE4aAn/release/deps/libfutures_core-103b609c73ea6c6e.rmeta --extern futures_util=/tmp/cargo-installNE4aAn/release/deps/libfutures_util-6099575e8d3664dd.rmeta --extern http=/tmp/cargo-installNE4aAn/release/deps/libhttp-35946bd5c1aadf9b.rmeta --extern http_body=/tmp/cargo-installNE4aAn/release/deps/libhttp_body-af4db5ab69dc3d21.rmeta --extern hyper=/tmp/cargo-installNE4aAn/release/deps/libhyper-12e96715791fbefc.rlib --extern hyper_rustls=/tmp/cargo-installNE4aAn/release/deps/libhyper_rustls-bd3e12189a0ce6f5.rmeta --extern ipnet=/tmp/cargo-installNE4aAn/release/deps/libipnet-397851caef7963a7.rmeta --extern lazy_static=/tmp/cargo-installNE4aAn/release/deps/liblazy_static-83d805e7372df934.rmeta --extern log=/tmp/cargo-installNE4aAn/release/deps/liblog-17dd83666760fff6.rmeta --extern mime=/tmp/cargo-installNE4aAn/release/deps/libmime-02e3bddf6a931cf1.rmeta --extern percent_encoding=/tmp/cargo-installNE4aAn/release/deps/libpercent_encoding-fa31394cd0ef06b4.rmeta --extern pin_project_lite=/tmp/cargo-installNE4aAn/release/deps/libpin_project_lite-77c47a0bab90a3d2.rmeta --extern rustls=/tmp/cargo-installNE4aAn/release/deps/librustls-f4493af0cac97b24.rmeta --extern serde=/tmp/cargo-installNE4aAn/release/deps/libserde-ec5b4773efe952b0.rmeta --extern serde_urlencoded=/tmp/cargo-installNE4aAn/release/deps/libserde_urlencoded-342809cc4872a293.rmeta --extern tokio=/tmp/cargo-installNE4aAn/release/deps/libtokio-0ca69eb4de11e028.rmeta --extern tokio_rustls=/tmp/cargo-installNE4aAn/release/deps/libtokio_rustls-aa6360ee20838f20.rmeta --extern tokio_socks=/tmp/cargo-installNE4aAn/release/deps/libtokio_socks-c112eb463b37c370.rmeta --extern url=/tmp/cargo-installNE4aAn/release/deps/liburl-fbea4354aeb32e1a.rmeta --extern webpki_roots=/tmp/cargo-installNE4aAn/release/deps/libwebpki_roots-fdfa361aa7020324.rmeta --cap-lints allow -L native=/tmp/cargo-installNE4aAn/release/build/ring-a3fe10e9f2fee5e2/out`
error: could not compile `routinator-ui`

Caused by:
  process didn't exit successfully: `rustc --crate-name routinator_ui --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-ui-0.3.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C metadata=4a71a71ec76a3fc2 -C extra-filename=-4a71a71ec76a3fc2 --out-dir /tmp/cargo-installNE4aAn/release/deps -L dependency=/tmp/cargo-installNE4aAn/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `routinator v0.10.2`, intermediate artifacts can be found at `/tmp/cargo-installNE4aAn`

Caused by:
  build failed

**Comment by partim** [comment]
Looks like your build machine doesn’t have enough memory. We did a few tests and it seems a machine with 2 GB memory is necessary. We’re looking into improving the build process to be less memory hungry. I have created [routinator-ui #42](https://github.com/NLnetLabs/routinator-ui/issues/42) for that.

**Comment by devops365** [comment]
Yes indeed ! I increased this machine to 3GB of ram and it worked perfectly.

Thank you
