### ISSUE TITLE
Routinator in closed environment - switch|flag to avoid installing TALs

### ISSUE THREAD

**Issue by netravnen** [NLnetLabs/routinator#75]
Would it be possible to implement a switch|flag (e.g. `--no-install-tals`) at install time. To tell Routinator to _not_ install them.

Case: This can be useful in the context of running Routinator in a closed environment _not_ connected to the internet. E.g. Freifunk, DN42, ICVPN, Closed Lab Environment (Where you do not need route certificates for the whole Internet.) So as to avoid Routinator refusing to start. Because 4 out of 5 TALs are present. Currently removing all TALs manually after install is finished has the same effect. But I would like to be able to do this upon install time. (Currently I myself run Routinator for an ASN in DN42. Where this caused me a bit of head egg at the beginning. Before I figured it out.)

NB: Without the public TALs. I currently for my DN42 network use an [exception file](https://github.com/netravnen/dn42-roa-export) with Routinator. Works great for the experience. Where I do not need all ~70k signed certificates for routes on the public Internet / DFZ.

**Comment by partim** [comment]
Routinator will only install the TALs if the TAL directory does not exists. So, if you create the TAL directory first (by default ~/.rpki-cache/tals) and put whatever TALs you want in there, you should be fine.

That said, we are planning on switching this automagic approach to a explicit ‘init’ command.

**Comment by netravnen** [comment]
Could adding a [snippet the the README.md](https://github.com/NLnetLabs/routinator/commit/be71d0b06fb3c5407ea70fd6659e584c93fb14ae) file for a start be enough?

**Comment by partim** [comment]
It is mentioned in the [manual page](https://github.com/NLnetLabs/routinator/blob/master/doc/routinator.1#L406) which we consider the canonical documentation. I guess we should mention that – I also want to move it to a more readable format.

Give me a day or two to sort this out as I am traveling right now.

**Comment by netravnen** [comment]
Reading the manual page. When starting Routinator for the first time. `~/.rpki-cache/tals` well be created per default. And Routinator will populate it with the TALs of the five Regional Internet Registries...
...
So avoiding the `tals` directory to be created at first-run time is impossible? I therefor am forced to go in and remove the `tals` directory afterwards. To be able to run Routinator without loading the official RIR tals? (was maybe hoping for a switch (e.g. `--no-create-tals-dir`) to disable this behavior of there being created a `tals` dir altogether.)

**Comment by partim** [comment]
‘If the specified or default directory does not exist, Routinator will try to create it and populate it […]’

So, `mkdir $TAL_DIR` and then run `routinator -t $TAL_DIR` should be exactly what you want.
