### ISSUE TITLE
Build multi-architecture docker images

### ISSUE THREAD

**Issue by bladeswords** [NLnetLabs/routinator#763]
It would be great if the ARM instruction set was supported in the docker builds published to dockerhub.  This would enable easy use routinator on small devices such as raspberry pi and also modern cloud such as AWS graviton instances.

**Comment by ximon18** [comment]
Hi @bladeswords,

Thanks for the request, the description of potential use cases and most of all for a PR!

As it happens I just extended the Krill GitHub Actions workflows to publish multi-arch Docker images to Docker Hub for several ARM variants.

I'll take a look at your PR.

Ximon

**Comment by bladeswords** [comment]
Amazing, if you can reuse what you did for Krill - keep it going.  It does seem like a better way forward over using QEMU.
