### ISSUE TITLE
ASN don't update

### ISSUE THREAD

**Issue by alxobando** [NLnetLabs/routinator#787]
HI, prefix 30.51.243.0/24 is in https://rpki-validator.ripe.net/ui/38.51.243.0%2F24?validate-bgp=true in old ASN, new ASN used to prefix is [272869]. Is posible update?

**Comment by alxobando** [comment]
38.51.243.0/24 attach radb
![RADB](https://user-images.githubusercontent.com/1790243/192112675-ba9c46c4-3775-4b1d-9480-af0dec9599b1.PNG)

**Comment by AlexanderBand** [comment]
The Routinator [user interface](https://routinator.docs.nlnetlabs.nl/en/stable/user-interface.html) uses BGP information based on [RISWhois](https://www.ris.ripe.net/dumps/) data, which is part of the RIPE NCC’s [Routing Information Service](https://ris.ripe.net/) (RIS). This data set is currently updated every 8 hours. You can see the freshness of the data in the UI.
