### ISSUE TITLE
Remove `--accept-arin-rpa` and `routinator-init` as they are no longer required

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#788]
https://www.arin.net/announcements/20220926/

**Comment by ximon18** [comment]
Some things to do:
- Update the installation instructions, initialisation page, building page and manual page at RtD.
- Update the man page.
- Update the README.
- Update the README at Docker Hub.
- Pre-init Routinator inside the Docker image including all TALs?
- Remove use of `--accept-arin-rpa` in GitHub Actions `pkg` workflow, specifically in `pkg/test-scripts/test-routinator.sh`.

**Comment by AlexanderBand** [comment]
After installation with `apt`, immediately start running with the default settings en have systemd enable start at boot.

**Comment by ximon18** [comment]
Removing `routinator-init` and changing the systemd service to be enabled and to start automatically requires additional changes in the following places:
- Remove the `pkg/common/routinator-init` script.
- `Cargo.toml` should no longer bundle the `routinator-init` script for DEB and RPM packages.
- More updates to the `installation` and `initialisation` docs pages.
- Remove the invocation of `routinator-init` entirely from `pkg/test-scripts/test-routinator.sh` and update it to verify that the service is started automatically, rather than starting it via `systemctl start`.

**Comment by ximon18** [comment]
Should we leave `routinator-init` but replace it by a dummy `This command no longer needs to be run` or similar for one release?

**Comment by ximon18** [comment]
For upgrade of an existing deployment, maybe the systemd service shouldn't be started if it isn't already running?

**Comment by ximon18** [comment]
@AlexanderBand: Surely not the entirety of it as `routinator init` will still exist, e.g. to list TALs and choose to do custom TAL setups etc?

**Comment by partim** [comment]
So, the proposed plan for this is: Get rid of installing TAL files entirely.

By default, Routinator will use the five RIR TALs that are baked into the binary. If you want to install your own TAL files, you need to explicitly specify a `--tal-dir` and Routinator will use the files in that directory in addition to the built-in TALs. If you don’t want the built-in TALs, you can say so via a new `--no-rir-tals` options.

How does that sound?

**Comment by ximon18** [comment]
> Should we leave `routinator-init` but replace it by a dummy `This command no longer needs to be run` warning or similar for one release?

We discussed this and concluded that the script would be removed entirely.

**Comment by ximon18** [comment]
> For upgrade of an existing deployment, maybe the systemd service shouldn't be started if it isn't already running?

The implementation starts the service on the basis that normal usage previously would be to do init then start the service and if the user hadn't done that already they still would have intended to do so, and normal behaviour now on initial install is to start so this makes the upgrade and initial install behaviour the same.
