### ISSUE TITLE
No valid trust anchor

### ISSUE THREAD

**Issue by bruzzese95** [NLnetLabs/routinator#789]
Hello everyone, I am having a problem with the configuration of Routinator.
I installed it on a machine in my virtual network and gave the following command:
**routinator init --rir-tals --accept-arin-rpa**

The response is:
**Created local repository directory /root/.rpki-cache/repository
Installed 5 TALs in /root/.rpki-cache/tals**

When I try to get the ROAs with the command **routinator -v vrps** I get the problem:
**No valid trust anchor for TAL afrinic
No valid trust anchor for TAL apnic
No valid trust anchor for TAL arin
No valid trust anchor for TAL lacnic
No valid trust anchor for TAL ripe
ASN,IP Prefix,Max Length,Trust Anchor**

What could be the problem?

Thanks.

**Comment by partim** [comment]
Can you add another `-v` to your command to get more output? (I.e., `routinator -vv vrps`). My guess would be that you have networking issues, which the extra `-v` should expose.

**Comment by bruzzese95** [comment]
It was a problem of DNS, when properly setted routinator works in the correct way.
Thank you.
