### ISSUE TITLE
Docker  Image don't work with IPv6

### ISSUE THREAD

**Issue by ruben-herold** [NLnetLabs/routinator#805]
hi,

the docker image is not able to run on ipv6. It only listen to ipv4.

**Comment by ximon18** [comment]
Hi @ruben-herold,

Thanks for the issue report.

My apologies if you are already aware of this but if not it is important to note that Docker [doesn't support IPv6 out-of-the-box](https://docs.docker.com/config/daemon/ipv6/).

Typically with Docker containers the listening is restricted to local ports within the container itself and listen ports are "published" to the host so that connections to the host port are forwarded to the container port. In the case of Routinator this would be the HTTP and RTR service ports (by default 3323 and 8323 when using the defaults with the Routinator Docker image).

I am able to run Routinator on an IPv6 capable host and in a container that has an IPv6 address and IPv6 connectivity to the outside world, e.g.: _(in this case my test host already has a correctly configured Docker daemon to enable IPv6 use within containers)_

```
$ docker volume create routinator-tals
routinator-tals

$ docker run --rm \
    -v routinator-tals:/home/routinator/.rpki-cache/tals nlnetlabs/routinator:v0.11.3 \
    init -f --tal ripe
Created local repository directory /home/routinator/.rpki-cache/repository
Installed 1 TALs in /home/routinator/.rpki-cache/tals

$ docker run -d \
    --restart-unless-stopped \
    --name routinator \
    -p 3323:3323 \
    -p 9556:9556 \
    -v routinator-tals:/home/routinator/.rpki-cache/tals \
    nlnetlabs/routinator:v0.11.3

$ docker exec -it routinator ip -6 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
172: eth0@if173: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 state UP 
    inet6 2a02:a467:c141::242:ac11:2/80 scope global flags 02 
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link 
       valid_lft forever preferred_lft forever

$ docker exec -it routinator ping -6 google.com
PING google.com (2a00:1450:400e:810::200e): 56 data bytes
64 bytes from 2a00:1450:400e:810::200e: seq=0 ttl=59 time=4.978 ms
64 bytes from 2a00:1450:400e:810::200e: seq=1 ttl=59 time=7.204 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 4.978/6.091/7.204 ms
```

I can access the published ports from the host, e.g.: 

```
$ wget -qO- http://127.0.0.1:9556/status | head -n 20
version: routinator/0.11.3
serial: 0
last-update-start-at:  2022-10-17 12:28:09.699283465 UTC
last-update-start-ago: PT580.776838826S
last-update-done-at:   2022-10-17 12:36:21.280583652 UTC
last-update-done-ago:  PT89.195538639S
last-update-duration:  PT491.581300187S
valid-roas: 33403
valid-roas-per-tal: ripe=33403 
vrps: 180386
vrps-per-tal: ripe=180386 
unsafe-vrps: 3
unsafe-filtered-vrps-per-tal: ripe=3 
locally-filtered-vrps: 0
locally-filtered-vrps-per-tal: ripe=0 
duplicate-vrps-per-tal: ripe=1 
locally-added-vrps: 0
final-vrps: 180385
final-vrps-per-tal: ripe=180385 
stale-count: 0
```

In what way do you mean that it does not work on IPv6?

Thanks,

Ximon

**Comment by ruben-herold** [comment]
@ximon18  try:

wget -qO- http://[::1]:9556/status | head -n 20 instead. this will not work

Cause routinator inside the container listen on 0.0.0.0 not on :: which would also open an ipv6 listener. 
My management vlan is ipv6 only. I have no problem to give the container a ipv6 and make it reachable 

Ho I do it:

/etc/docker/daemon.json:

```
{
  "ipv6": true,
  "fixed-cidr-v6": "64:ff9b:102::/64"
}

```
then add masquerade for the network.

After container start it has an IPv6 from that network but the docker-proxy won't work and I can' t reach the service via IPv6 cause it only binds to ipv4.

**Comment by ximon18** [comment]
Hi @ruben-herold,

You can configure Routinator to listen on all addresses using e.g. `--http [::]:9556`:

```
docker run -d \
    --restart-unless-stopped \
    --name routinator \
    -p 3323:3323 \
    -p 9556:9556 \
    -v routinator-tals:/home/routinator/.rpki-cache/tals \
    nlnetlabs/routinator:v0.11.3 \
    server --http [::]:9556
```

Then this works for me:

```
$ wget -qO- http://[::1]:9556/status | head -n 20
version: routinator/0.11.3
serial: 0
last-update-start-at:  2022-10-17 13:12:09.450315255 UTC
last-update-start-ago: PT512.688337177S
last-update-done-at:   2022-10-17 13:20:12.104081568 UTC
last-update-done-ago:  PT30.034570864S
last-update-duration:  PT482.653766313S
valid-roas: 33410
valid-roas-per-tal: ripe=33410 
vrps: 180403
vrps-per-tal: ripe=180403 
unsafe-vrps: 3
unsafe-filtered-vrps-per-tal: ripe=3 
locally-filtered-vrps: 0
locally-filtered-vrps-per-tal: ripe=0 
duplicate-vrps-per-tal: ripe=1 
locally-added-vrps: 0
final-vrps: 180402
final-vrps-per-tal: ripe=180402 
stale-count: 0
```

**Comment by ximon18** [comment]
FYI this is  what I did on my system:

```
$ cat /etc/docker/daemon.json
{
  "ipv6": true,
  "fixed-cidr-v6": "2a02:a467:c141::1/80"
}

$ sudo sysctl net.ipv6.conf.default.forwarding=1
$ sudo sysctl net.ipv6.conf.all.forwarding=1
$ sudo ip6tables -t nat -A POSTROUTING -s 2a02:a467:c141::1/80 -j MASQUERADE
$ sudo systemctl docker restart

$ docker network inspect bridge | grep -i ipv6
        "EnableIPv6": true,
                "IPv6Address": "2a02:a467:c141::242:ac11:2/80"
```

With:

```
$ cat /etc/fedora-release 
Fedora release 36 (Thirty Six)

$ uname -srvip
Linux 5.19.14-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 5 21:31:17 UTC 2022 x86_64 x86_64

$ docker --version
Docker version 20.10.18, build b40c2f6
```

**Comment by ruben-herold** [comment]
hi,

thx :
`
 server --http [::]:9556
`

This seems do be doing it.  Could we document it? 

Also It would be nice to fix the ports in the install manual at: 

https://routinator.docs.nlnetlabs.nl/en/stable/installation.html

**Comment by ximon18** [comment]
Hi @ruben-herold,

I'm happy to hear that!

`--http` is [already documented](https://routinator.docs.nlnetlabs.nl/en/stable/daemon.html?highlight=ipv6#) but not specifically in the context of Docker.

We have changes scheduled to the Docker related documentation for PR #796 which simplifies the use of Docker considerably. I will also propose some changes to address the confusing state of the documentation regarding HTTP port numbers 8323 and 9556, especially in the Docker context. I think it's also worth clearly noting the default command run by the Docker image and how to override it, e.g. to control the HTTP listen interface.

I will leave this issue open until the documentation changes have been made.

Ximon

**Comment by ximon18** [comment]
I've created https://github.com/NLnetLabs/routinator/issues/808 to track the incorrect port number reference in the Docker documentation for Routinator.

**Comment by ximon18** [comment]
@ruben-herold: One more thing to note: if you wish to have a router connect to Routinator using the RTR protocol you probably also need to expose the RTR port on IPv6 as well, e.g. `--rtr [::]:3323`.

**Comment by ximon18** [comment]
@ruben-herold: You can see the proposed documentation changes [here](https://github.com/NLnetLabs/routinator/pull/809) and a rendered version of the final page can be seen [here](https://routinator--809.org.readthedocs.build/en/809/installation.html). Feedback is welcome!

Ximon

**Comment by ruben-herold** [comment]
Thx looks great...
