### ISSUE TITLE
`rpmlint` on CentOS 7 reports `missing-call-to-chdir-with-chroot`

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/routinator#822]
From: https://github.com/NLnetLabs/routinator/actions/runs/3539538054/jobs/5941562438#step:19:138

```
rpmlint version 1.5 Copyright (C) 1999-2007 Frederic Lepied, Mandriva
routinator.x86_64: W: manpage-not-compressed gz /usr/share/man/man1/routinator.1
routinator.x86_64: W: summary-ended-with-dot C An RPKI relying party software.
routinator.x86_64: W: no-url-tag
routinator.x86_64: E: missing-call-to-chdir-with-chroot /usr/bin/routinator
routinator.x86_64: W: conffile-without-noreplace-flag /etc/routinator/routinator.conf
1 packages and 0 specfiles checked; 1 errors, 4 warnings.
```

Note the error `E: missing-call-to-chdir-with-chroot /usr/bin/routinator` that was reported.

It may be relevant to note that this same `rpmlint` check was reported as [causing false positives](https://github.com/rpm-software-management/rpmlint/issues/84), with the issue apparently being added in some way to the `rpmlint` 2.0 milestone. The latest version of `rpmlint` (2.4.0 at the time of writing) does not seem to contain this check nor does the source code seem to contain any other checks relating to `chroot`. So, this may not be a cause for concern. If you are interested the source code relating to this check in `rpmlint` 1.5 can be seen [here](https://github.com/rpm-software-management/rpmlint/blob/rpmlint-1.5/BinariesCheck.py#L153) and [here](https://github.com/rpm-software-management/rpmlint/blob/rpmlint-1.5/BinariesCheck.py#L466).

However, one other related point that may be worth investigating is that [another user that encountered this issue](https://jira.mariadb.org/browse/MDEV-11962) said regarding the application in question (not Routinator):

> This executable appears to call chroot without using chdir to change the current directory. This is likely an error and permits an attacker to break out of the chroot by using fchdir. While that's not always a security issue, this has to be checked.

Glancing at the Routinator source code I see that it makes a call to `nix::chroot()` but not to `nix::chdir()` so perhaps Routinator should do a `chdir` here like the issue reporter above mentioned?

Regarding the failed workflow run, that was a test with the latest development version of [Ploutos](https://github.com/NLnetLabs/ploutos/). Given that there is a question mark over the reliability and even existence of this check in `rpmlint` I plan to make Ploutos ignore the `missing-call-to-chdir-with-chroot` check by default.

**Comment by partim** [comment]
Turns out it only changes the working directory if you configure it to do so. I suppose if that isn’t set but chroot is, we should change into the change root directory.
