### ISSUE TITLE
rpm file for centos7 b0rked

### ISSUE THREAD

**Issue by philfry** [NLnetLabs/routinator#829]
Hi all,

when using `dnf` with CentOS 7 the routinator package (tested 0.10.0 to 0.12.0) is reinstalled with every `dnf upgrade`. Using `yum` or with RHEL8 this doesn't happen.

```
[root@4e24bac2e10f ~]# dnf --setopt=tsflags=noscripts -y install routinator
Last metadata expiration check: 0:01:09 ago on Mon Dec 12 13:39:26 2022.
Dependencies resolved.
=======================================================================================================================
 Package                      Arch                     Version                       Repository                   Size
=======================================================================================================================
Installing:
 routinator                   x86_64                   0.12.0-1                      nlnetlabs                   4.1 M

Transaction Summary
=======================================================================================================================
Install  1 Package

Total download size: 4.1 M
Installed size: 9.2 M
Downloading Packages:
routinator-0.12.0-1.x86_64.rpm                                                          14 MB/s | 4.1 MB     00:00    
-----------------------------------------------------------------------------------------------------------------------
Total                                                                                   14 MB/s | 4.1 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                               1/1 
  Verifying        : routinator-0.12.0-1.x86_64                                                                    1/1 

Installed:
  routinator-0.12.0-1.x86_64                                                                                           

Complete!
[root@4e24bac2e10f ~]# dnf upgrade routinator
Last metadata expiration check: 0:01:20 ago on Mon Dec 12 13:39:26 2022.
Dependencies resolved.
=======================================================================================================================
 Package                      Arch                     Version                       Repository                   Size
=======================================================================================================================
Reinstalling:
 routinator                   x86_64                   0.12.0-1                      nlnetlabs                   4.1 M

Transaction Summary
=======================================================================================================================

Total download size: 4.1 M
Installed size: 9.2 M
Is this ok [y/N]: n
Operation aborted.
```

Here's a buildfile to reproduce this issue:
[Buildfile.txt](https://github.com/NLnetLabs/routinator/files/10208551/Buildfile.txt)

**Comment by ximon18** [comment]
Thanks for reporting this @philfry, I'll look into it.

**Comment by ximon18** [comment]
Unfortunately I can't find any information about why `dnf` on CentOS 7 is choosing to reinstall an already installed package of the same version nor do my upgrade tests show anything useful in system logs or via the `dnf` extra output options such as `-d` or `-v` or `--debugsolver`.

**Comment by ximon18** [comment]
[This thread](https://unix.stackexchange.com/a/630720) is interesting as it talks about DNF maybe not being properly supoorted on CentOS 7 but also shows that the version available, 4.0.9, is old, and this is the same version I'm seeing installed in my DigitalOcean CentOS 7 Droplet. I wonder what happens with a newer version built from sources, i.e. is this a bug in the "old" DNF version.

**Comment by ximon18** [comment]
The CentOS 7package for 0.12.0 was built by [this GitHub Actions run](https://github.com/NLnetLabs/routinator/actions/runs/3436678780/jobs/5730579383). In the Verify step we see that `rpmlint` had the following to say about the built RPM:

```
+ rpmlint target/generate-rpm/routinator-0.12.0-1.x86_64.rpm
routinator.x86_64: W: manpage-not-compressed gz /usr/share/man/man1/routinator.1
routinator.x86_64: W: summary-ended-with-dot C An RPKI relying party software.
routinator.x86_64: E: no-buildhost-tag
routinator.x86_64: E: no-changelogname-tag
routinator.x86_64: W: no-url-tag
routinator.x86_64: E: no-binary
routinator.x86_64: W: conffile-without-noreplace-flag /etc/routinator/routinator.conf
1 packages and 0 specfiles checked; 3 errors, 4 warnings.
```

**Comment by ximon18** [comment]
I wonder if the same issue occurs with the 0.12.1-rc1 as that generates fewer `rpmlint` warnings and errors: (because the build process was updated since the 0.12.0 release)

```
 routinator.x86_64: W: manpage-not-compressed gz /usr/share/man/man1/routinator.1
routinator.x86_64: W: summary-ended-with-dot C An RPKI relying party software.
routinator.x86_64: W: no-url-tag
routinator.x86_64: W: conffile-without-noreplace-flag /etc/routinator/routinator.conf
```

**Comment by ximon18** [comment]
FYI the same issue occurs with the 0.12.1-rc1 RPM.

**Comment by ximon18** [comment]
Ah I see the changelog is available as part of the `dnf.spec` file, let me look through that to see if anything was changed in later versions that might explain why they work as expected and the 4.0.9.2 version does not.

**Comment by philfry** [comment]
Hi, thanks for your effort.

I compiled routinator myself, packaged it with `cargo generate-rpm` and came to the same result. IMO that cargo module is broken and/or triggers some bug in `dnf`, but I think it's not really worth investigating further. Starting with because building a newer `dnf` version for CentOS 7 is quite a pita.

I switched to building own packages :D
[routinator.spec.txt](https://github.com/NLnetLabs/routinator/files/10216527/routinator.spec.txt)

**Comment by ximon18** [comment]
I've narrowed it down a bit. It still happens in `dnf` 4.1.0 in Fedora 29, but doesn't happen in `dnf` 4.2.17 in Fedora 30.

**Comment by ximon18** [comment]
This line from the `dnf` [4.2.11 `dnf.spec` changelog](https://github.com/rpm-software-management/dnf/blob/master/dnf.spec#L660) might be responsible:

```
* Thu Sep 19 2019 Pavla Kratochvilova <pkratoch@redhat.com> - 4.2.11-1
- Improve modularity documentation (RhBug:1730162,1730162,1730807,1734081)
- Fix detection whether system is running on battery (used by metadata caching timer) (RhBug:1498680)
- New repoquery queryformat: %{reason}
- Print rpm errors during test transaction (RhBug:1730348) 
- Fix: --setopt and repo with dots
- Fix incorrectly marked profile and stream after failed rpm transaction check (RhBug:1719679)
- Show transaction errors inside dnf shell (RhBug:1743644)
- Don't reinstall modified packages with the same NEVRA (RhBug:1644241) <<<<<<<<<<<<<<<<<<<<<< THIS LINE
- dnf-automatic now respects versionlock excludes (RhBug:1746562)
```

**Comment by ximon18** [comment]
According to https://weldr.io/RPM-Dependencies/ NEVRA is:

> NEVRA refers to five pieces of information: Name, Epoch, Version, Release, Architecture. The Name, Epoch, Version, and Release are provided by the package maintainer, and the Architecture is determined by the build.

**Comment by ximon18** [comment]
Ah the commit message also references a different RedHat bug which looks interesting:

https://bugzilla.redhat.com/show_bug.cgi?id=1728252
> dnf should not take buildtime into account when upgrading packages

So maybe the missing `buildtime` header filed in the RPM generated by `cargo-generate-rpm` is the trigger for this behaviour, i.e. https://github.com/cat-in-136/cargo-generate-rpm/issues/20

**Comment by ximon18** [comment]
Ah it looks more like the "targeting" change might have been the issue, so really a bug in `dnf`. See: https://github.com/rpm-software-management/libdnf/pull/786 (linked from https://github.com/rpm-software-management/dnf/pull/1474 which is the PR for the commit that fixed https://bugzilla.redhat.com/show_bug.cgi?id=1728252).

**Comment by ximon18** [comment]
@philfry: I've raised an [issue](https://github.com/NLnetLabs/ploutos/issues/49) in the repository of the Ploutos packaging tool which Routinator uses to package its RPMs.

As this issue doesn't affect users of the default packaging tool in CentOS 7 (i.e. `rpm`, as `dnf` is not installed by default until CentOS 8), and because the Routinator repository doesn't control how the packaging works, I am inclined to close this Routinator issue.

Would that be okay with you?

**Comment by philfry** [comment]
Holy moly @ximon18, that's some nice research, thanks a lot! :+1: 
Yes, I'm fine with closing this issue.
