### ISSUE TITLE
Rsync errors: "timeout" and "no valid manifest"

### ISSUE THREAD

**Issue by daitepiva** [NLnetLabs/routinator#830]
Hello,

CentOS Linux release 7.9.2009 (Core) Routinator 0.12.0.

I see a lot of errors in /var/log/messages:
```
routinator[30189]: [WARN] rsync://rpki.sailx.co/repo/: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.2]
routinator[30189]: [WARN] rsync://rpki.sailx.co/repo/Sail-Internet-Inc/0/DFC5509768EA587E638D20680032E0FF122BD25A.mft: no valid manifest found.
routinator[30189]: [WARN] rsync://rrdp.taaa.eu/repo/: rsync error: timeout waiting for daemon connection (code 35) at socket.c(281) [Receiver=3.1.2]
routinator[30189]: [WARN] rsync://rrdp.taaa.eu/repo/rrdp-taaa-eu/0/AAFBF9DBE860335648F2AEABA124326B85374C47.mft: no valid manifest found.
```

It looks like only two rsync servers are available:
```
cd /var/lib/routinator/rpki-cache/rsync
du -ks *
0       rpki.0i1.eu
0       rpki1.rpki-test.sit.fraunhofer.de
36      rpkica.mckay.com
32      rpki.rand.apnic.net
0       rpki.sailx.co
0       rrdp.taaa.eu
0       rsync.rp.ki
```

What should I do with it?

Regards,
Malik.

**Comment by AlexanderBand** [comment]
There are several RPKI publication points that are poorly maintained, there is nothing you can do. [We see the same](https://routinator.do.nlnetlabs.nl/status).

All ~70 global RPKI publication points advertise that they make their data available over RRDP (which uses HTTPS), as well as rsync. All relying party software, including Routinator, will prefer to use RRDP if available and only when this fails repeatedly fall back to rsync. If rsync fails as well, Routinator will use cached data until it expires. To learn more about Routinator's data fetching strategy, please refer to the [documentation](https://routinator.docs.nlnetlabs.nl/en/stable/data-processing.html).
