### ISSUE TITLE
Log the certificate URL for a missing manifest

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator#840]
As a RPKI CA operator, it would help me if routinator printed the URL of the CA certificate of a missing manifest.

Right not it is hard to trace what CA certificate caused errors such as
```
[WARN] rsync://localhost/repository/DEFAULT/b3/7ec315-868b-4f62-b4e9-a30a229ef4c0/1/7OGkbJBH39pmTUMvpAqHY2ueycI.mft: no valid manifest found.
```

`find [path] -exec [openssll x509 to text]` followed by grep, or `rg -a [namehere]` are workarounds.

**Comment by partim** [comment]
This’ll lead to some rather cryptic log messages. I’m starting to think we might want to produce some more structured output for irregularities during a validation run?

**Comment by partim** [comment]
> Structured logging might be a lot.

For you to analyze or for us to implement? Because, honestly, I’m not sure it is all that much work for us – it might not be perfect in the beginning, but whether I am formatting a notice into a string or into a type that knows how to turn itself into some JSON doesn’t make all that much of a difference.

**Comment by ties** [comment]
> > Structured logging might be a lot.
> 
> For you to analyze or for us to implement? Because, honestly, I’m not sure it is all that much work for us – it might not be perfect in the beginning, but whether I am formatting a notice into a string or into a type that knows how to turn itself into some JSON doesn’t make all that much of a difference.

If the implementation effort is the same,  structurer logging is probably superior.

However, how does structured logging behave if no options are specified?

**Comment by partim** [comment]
My idea would be to provide a new HTTP endpoint that includes the log of the last validation run in JSON format. I suppose we could also log these JSON arrays (?) to a file if so configured.

**Comment by partim** [comment]
I’ve decided to just implement your original request for now. We’re going to look into providing a special repository consistency check mode as future work.
