### ISSUE TITLE
The same command behaves differently.

### ISSUE THREAD

**Issue by yushoyamaguchi** [NLnetLabs/routinator#855]
```
routinator -v --config /etc/routinator/routinator.conf update
routinator -v --config /etc/routinator/routinator.conf vrps
```
![1](https://user-images.githubusercontent.com/50731798/234672659-0725b62a-eb5d-4f36-b6af-2af7056b7e26.png)

```
routinator -v --config /etc/routinator/routinator.conf --rrdp-root-cert=rootCA.crt update
routinator -v --config /etc/routinator/routinator.conf --rrdp-root-cert=rootCA.crt vrps
```

![2b](https://user-images.githubusercontent.com/50731798/234673627-e5fc8e3c-2cd2-4934-8341-cbdcea5224f0.png)

```
routinator -v --config /etc/routinator/routinator.conf update
routinator -v --config /etc/routinator/routinator.conf vrps
```

![2c](https://user-images.githubusercontent.com/50731798/234673682-2463ae8c-5570-4734-90f1-84db9ed10363.png)

Like above pictures, vrps command's behavior are different before and after executing the command with ```--rrdp-root-cert``` option.

**Comment by partim** [comment]
That is correct. By default, Routinator only falls back to rsync if it hasn’t successfully managed to retrieve the repository via RRDP before and the copy it has isn’t older than an hour. In your third example, it uses this copy. There seems to be no ROAs in the RRDP-version of your repository, so the outputs in the second and third picture are empty.

You can change this behaviour through the [`rrdp-fallback-policy`](https://routinator.docs.nlnetlabs.nl/en/stable/manual-page.html#cmdoption-rrdp-fallback) option.

As an aside, the `vrps` command also updates the data, so you don’t need to run `update` first.

**Comment by yushoyamaguchi** [comment]
Thank you very much.

**Comment by yushoyamaguchi** [comment]
@partim 
I'm sorry for repeating questions.
In, the second image,  no RRDP error message was generated.
However, no validated ROA information is displayed.
Is there a way to know where error occured?

**Comment by partim** [comment]
You could try and run Routinator with `-vv` so it logs more details. If that doesn’t result in any message either, then it looks a bit like your RRDP repository doesn’t actually contain the ROA?
