### ISSUE TITLE
RTR Serial Number stuck at 0 in Routinator 0.13.0-dev

### ISSUE THREAD

**Issue by jayb-github** [NLnetLabs/routinator#856]
I am running an instance of Routinator 0.13.0-dev, configured to use all 5 RIR TALs.  The RTR Serial Number remains at zero, as seen from JunOS router 'canary':

jayb@canary> show validation session 12.0.1.148 detail    
Session 12.0.1.148, State: up, Session index: 3
  Group: rpki-validator, Preference: 100
  Local IPv4 address: 12.0.1.83, Port: 3323
  Refresh time: 300s
  Hold time: 600s
  Record Life time: 3600s
  Serial (Full Update): 0
  Serial (Incremental Update): 0
    Session flaps: 2
    Session uptime: 3d 02:53:34
    Last PDU received: 00:03:06
    IPv4 prefix count: 351314
    IPv6 prefix count: 76211

jayb@canary> 

The reason that 12.0.1.148 has delivered a reasonably-current set of VRPs is JunOS's behavior of sending periodic Reset Query PDUs.

For contrast, here's what an RTR session with a Routinator 0.12.1 now looks like:

jayb@canary> show validation session 12.0.1.162 detail    
Session 12.0.1.162, State: up, Session index: 7
  Group: rpki-validator, Preference: 100
  Local IPv4 address: 12.0.1.83, Port: 3323
  Refresh time: 300s
  Hold time: 600s
  Record Life time: 3600s
  Serial (Full Update): 205
  Serial (Incremental Update): 207
    Session flaps: 3
    Session uptime: 2d 02:12:01
    Last PDU received: 00:02:09
    IPv4 prefix count: 351314
    IPv6 prefix count: 76212

jayb@canary> 

Similar evidence is seen in Routinator INFO logs.

**Comment by partim** [comment]
Thanks for the report! I’ll fix it ASAP.
