### ISSUE TITLE
TAL's are not being placed if arin.tal is already existing

### ISSUE THREAD

**Issue by tuxis-ie** [NLnetLabs/routinator#86]
I deploy Routinator with ansible and thus place the arin.tal using get_url in Ansible. If you start routinator afterwards, it does not check if it has tals for all five RIRs but instead only runs with output of Arin.

Removing the tals directory creates all the tals and the fake Arin one.

**Comment by partim** [comment]
We are going to change the whole strategy around setting up the TAL directory in one of the next versions and replace it with an `init` command.
