### ISSUE TITLE
Validity checker fails with JSON input example in docs

### ISSUE THREAD

**Issue by cpbruton** [NLnetLabs/routinator#860]
In the [Validity Checker documentation](https://routinator.docs.nlnetlabs.nl/en/stable/validity-checker.html), the following example is provided as an example JSON input file `beacons.json`:
```
{
  "routes": [{
      "asn": "AS12654",
      "prefix": "93.175.147.0/24"
    },
    {
      "asn": "AS12654",
      "prefix": "2001:7fb:fd02::/48"
    }
  ]
}
```
When I follow the example to validate this input file, Routinator exits with an error:
```
% routinator validate --json --input beacons.json
Failed to read input file 'beacons.json': invalid type: string "12654", expected u32 at line 3 column 20'
```

I then changed the input to the following, changing `"AS12654"` to simply `12654`:
```
{
  "routes": [{
      "asn": 12654,
      "prefix": "93.175.147.0/24"
    },
    {
      "asn": 12654,
      "prefix": "2001:7fb:fd02::/48"
    }
  ]
}
```
After this change, the operation succeeds:
```
% routinator validate --json --input beacons.json
[snip]
{
  "validated_routes": [
    {
      "route": {
        "origin_asn": "AS12654",
        "prefix": "93.175.147.0/24"
      },
      "validity": {
        "state": "invalid",
        "reason": "as",
[snip]
```

At the minimum, either the software or the documentation needs to be fixed so that the example works correctly. Note that the JSON _output_ returns the ASN in the `"AS12345"` string format, not as an integer, so it's inconsistent if the input is required to be an integer.

But I would recommend allowing some flexibility in how the ASN is ingested. It would be great if all of these formats were accepted:

```
"asn": 12654
"asn": "12654"
"asn": "AS12654"
```

I see this issue both in the latest release v0.12.1 and in v0.13.0-dev (both compiled from source today using `cargo` on macOS).
```
% routinator --version
Routinator 0.12.1
% target/debug/routinator --version
Routinator 0.13.0-dev
% git show
commit 953671cd467436052b3e7844b77a8fef8beed21e (HEAD -> main, origin/main, origin/HEAD)
Author: Martin Hoffmann <martin@nlnetlabs.nl>
Date:   Mon May 1 14:21:04 2023 +0200
```

**Comment by partim** [comment]
Thank you for the report! The intention was indeed to accept both – I suspect older versions of Routinator did – but this fell victim to some refactoring along the way.

This will be fixed ASAP.
