### ISSUE TITLE
Debian 12 bookworm packages

### ISSUE THREAD

**Issue by crami** [NLnetLabs/routinator#880]
Hi

 Debian 12 bookworm was release some weeks ago. When do you plan to release Debian packages for this release?

**Comment by partim** [comment]
The upcoming 0.13 will be packaged for _bookworm._

**Comment by Showfom** [comment]
Still no packages for Debian 12

```
root@routinator ~ # curl https://packages.nlnetlabs.nl/linux/debian/dists/bookworm/main/binary-amd64/Packages
```

**Comment by partim** [comment]
Apologies. 0.13 got delayed due to the summer holidays. It should arrive real soon.

**Comment by XioNoX** [comment]
Thanks! Out of curiosity, do you have plans to make the packages available in the official Debian repositories? That would make it much more convenient for the users.

**Comment by partim** [comment]
Unfortunately, there is a rather long tail of things to be done for packaging Routinator for official Debian and we don’t really have the experience (or resources) to do that currently.
