### ISSUE TITLE
RHEL9-repo repomd.xml error

### ISSUE THREAD

**Issue by pwcazenave** [NLnetLabs/routinator#884]
This is pretty much the same issue as #806.

I'm trying to install routinator on RHEL9 with the following repo config:

```
[nlnetlabs]
name=NLnet Labs
baseurl=https://packages.nlnetlabs.nl/linux/centos/$releasever/main/$basearch
enabled=1
```

When I run `dnf search routinator` I get:

```
NLnet Labs                                                                              915  B/s | 224  B     00:00
Error: Failed to download metadata for repo 'nlnetlabs': repomd.xml parser error: Element <repomd> was not found - Bad repomd file
```

If I change the `baseurl` to the `poposed` branch, it works OK:

```
[nlnetlabs]
name=NLnet Labs
baseurl=https://packages.nlnetlabs.nl/linux/centos/$releasever/proposed/$basearch
enabled=1
```

A `dnf search routinator` yields:

```
Last metadata expiration check: 0:19:34 ago on Fri 14 Jul 2023 10:36:58 BST.
=========================================== Name Exactly Matched: routinator ===========================================
routinator.x86_64 : An RPKI relying party software.
```

I the 9-main repo temporarily down?

Thanks,

Pierre

**Comment by ximon18** [comment]
There has never been a release of Routinator to the main repo for RHEL 9 as the last official release of Routinator only had a package for RHEL 8, not for RHEL 9.

The latest release candidate of Routinator was just published and it does have a RHEL 9 package, but as an RC gets published to the proposed repo, not the main repo.

When the final release is ready it will be published to the RHEL 9 main repo.

**Comment by partim** [comment]
0.12.2 should have appeared in the repository.
