### ISSUE TITLE
Header/footer lines of EC TLS key files

### ISSUE THREAD

**Issue by johannesmoos** [NLnetLabs/routinator#908]
This is related to https://github.com/NLnetLabs/routinator/issues/825

Routinator does not accept key files with header and footer lines like the following:
```
 -----BEGIN EC PRIVATE KEY-----
 -----END EC PRIVATE KEY-----
```

This results in
`[ERROR] TLS key file <keyfile> does not contain any usable keys`

Removing `EC` does the trick.

**Comment by partim** [comment]
Of course I’m still holding it wrong. Thanks for the report! I’ll add it to the list of little things to be fixed with the next release.
