### ISSUE TITLE
Default prometheus exporter port for routinator

### ISSUE THREAD

**Issue by wk** [NLnetLabs/routinator#91]
Prometheus maintains a list of allocations of [default ports](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) for exporters, and routinator has been added to the list as port `9556`. 

This could be reflected as a recommendation or a default in `config.rs`, or in documentation (`README.md`, `doc/routinator.1`) as a value for `listen-http`.

**Comment by partim** [comment]
Thanks for reserving the port!

We currently don’t spin up the HTTP server if `listen-http` is missing; I feel we should probably keep it that way. So maybe this should go into the documentation.

**Comment by wk** [comment]
Addressed in #92, an example of `listen-http` was missing from the sample `routinator.conf` file, so that was added as well, featuring the same allocated port number.
