### ISSUE TITLE
Initial version negotiation is broken because of bad error PDU version

### ISSUE THREAD

**Issue by cjeker** [NLnetLabs/routinator#919]
When running a router with RTR version 11 (I know that version is unsupported) routinator v0.13.0 answers with a
version 11 Code 4 error PDU. This breaks version negotiation since the router has no idea what it should downgrade to.

```
rtr routinator: state change closed -> negotiation, reason: connection open
rtr routinator: got error report with version 11, my version 11
rtr routinator: received error: Unsupported Protocol Version: only versions 0 to 2 supported
rtr routinator: sending error: Unsupported Protocol Version: negotiation failed
rtr routinator: state change negotiation -> error, reason: sent error
```

Fix: Routinator should never send out a PDU with a version it does not handle itself (in this case version 2).

**Comment by partim** [comment]
From what I’m reading in the Sidrops discussion, the preferred solution would be to not send an error but respond with the version set to the best version supported. Is that correct?

**Comment by partim** [comment]
Also, currently the implementation closes the connection with an error if the client changes the version during a session. It is not entirely clear to me whether that is as intended or not.

**Comment by cjeker** [comment]
> From what I’m reading in the Sidrops discussion, the preferred solution would be to not send an error but respond normally with the version set to the best version supported. Is that correct?

This is currently a big debate. RFC8210 allows to either send an error pdu 
with code 4 and the lowered version or do the downgrade and send a cache 
response or cache reset with the lowered version.

Both is fine IMO. The problem right now is that the error PDU is sent with 
the received version (which routinator does not support).

I think fixing the wrong version in the error PDU should be quick fix and a priority.
The change to do the implicit downgrade can happen later once sidrops managed to come to a conclusion.

**Comment by cjeker** [comment]
> Also, currently the implementation closes the connection with an error if the client changes the version during a session. It is not entirely clear to me whether that is as intended or not.

Are you talking about the code 8 errors (unexpected version error)? Or the code 4 (unsupported version error) which are only used during version negotiation?
 
Again closing the connection is IMO fine. Especially for code 8 errors since something is not right.
Right now closing the connection is probably the best reaction for most errors. One could argue that during version negotiation a code 4 error should not close the connection (and therefor it should no longer be considered fatal).
In the long run this would be nice but I don't see this as a requirement for proper operation -- it is merely an optimisation.

**Comment by partim** [comment]
> Are you talking about the code 8 errors (unexpected version error)? Or the code 4 (unsupported version error) which are only used during version negotiation?

Looks like it’s responding with an 8, so that’s all fine, then.

I’ll fix the version in the initial response and make that part of 0.13.1 which should have a first RC very early next week.

**Comment by cjeker** [comment]
Sounds great, thanks.

**Comment by partim** [comment]
In related news, given that there is zero response by the draft authors regarding the ASPA PDU, I will remove version 2 support again in the next version rather than sending PDUs that may or may not be broken in the final RFC.

**Comment by cjeker** [comment]
> In related news, given that there is zero response by the draft authors regarding the ASPA PDU, I will remove version 2 support again in this release rather than sending PDUs that may or may not be broken in the final RFC.

It is a big nightmare that all of ASPA development is stalled by something that is so simple.
My plan is to use the format we all agreed on and not the one from the latest draft:

```
5.12. ASPA PDU

0          8          16         24        31
.-------------------------------------------.
| Protocol |   PDU    |          |          |
| Version  |   Type   |   Flags  |   zero   |
|    2     |    11    |          |          |
+-------------------------------------------+
|                                           |
|                 Length                    |
|                                           |
+-------------------------------------------+
|                                           |
|    Customer Autonomous System Number      |
|                                           |
+-------------------------------------------+
|                                           |
~    Provider Autonomous System Numbers     ~
|                                           |
~-------------------------------------------~
```

See also https://mailarchive.ietf.org/arch/msg/sidrops/TV0Gzys0J7M3PNwWZrAKWshGpSU/ for the full section 5.12 text.
