### ISSUE TITLE
Cisco IOS XE documentation

### ISSUE THREAD

**Issue by kmorin18** [NLnetLabs/routinator#930]
Hello,

The Routinator docs simply link to a PDF for the configuration of Cusco IOS XE routers
However, that documentation is incomplete.
It does not cover any pas the password configurations, making configuration impossible in a mixed IOS XR and IOS XE environment.

Said documentation stops at "bgp rpki server tcp 10.0.0.10 port 3323 refresh 600", but that command is incomplete.
It required a TCP MD5 password, and without it, it is impossible to configure an SSH password.

Here is the full syntax:
_bgp rpki server tcp 10.0.0.10 port 3323 refresh 600 password 0 ***md5-password*** user ***ssh-user*** password ***ssh-password*** local-port_

The first password is the TCP MD5 password, and the second one is the SSH user password
The "0" means an unencrypted MD5 password follows

**Comment by AlexanderBand** [comment]
I added links to router documentation as a helpful pointer, rather than attempting to (re)write authoritative documentation for each vendor. Do you perhaps have a better link for IOS XE config? I'm happy to change it.

**Comment by kmorin18** [comment]
Thanks for your reply Alex!
I've looked everywhere and indeed Cisco doesn't have a proper public documentation.
Maybe just to save everyone's time a mention about IOS XE devices (ASR 1000 series) could be added simply to mention that special MD5 password authentication may be required?

I'm still looking for the proper config, I'll be happy to share it once we have it working

**Comment by kmorin18** [comment]
Ends up the firewall was the issue. IOS Xe doesn't have a source interface setting. Loopback was white listed, but the Routinator was getting the request from a point to point OSPF link IP
