### ISSUE TITLE
Routinator Doesn't Listen On IPv6 By Default

### ISSUE THREAD

**Issue by Rishi556** [NLnetLabs/routinator#936]
A little while ago, I'd moved an instance of Routinator onto a IPv6 only server(with NAT64 in case any data fetching needs v4). Swapped out the address on the router and didn't think much more of it. Today I noticed that RPKI validation wasn't taking place, and after doing some digging, realized that the router couldn't connect to Routinator. More digging, had me find out that Routinator wasn't listening on v6 and stumbled onto the folloing line:

https://github.com/NLnetLabs/routinator/blob/c20ac6e942a7af39686da9d91b813bd9f0d0be4d/etc/routinator.conf.example#L139

Is there a reason that listening on IPv6 isn't done by default, or just something not thought up of when the the default config was created?

**Comment by partim** [comment]
Note how this a localhost address, so if you are just uncommenting this line, it won’t listen on a public V4 address either. This was chosen as a safe default – it is fine for testing but it won’t make Routinator be open to the entire world by accident.

As an aside: If you do want to it to listen an all interfaces, the notation differs slightly for Linux and the BSDs: On Linux `[::]` includes IPv4 but on the BSDs you need two stanzas with `0.0.0.0` and `[::]`.

**Comment by Rishi556** [comment]
Yup, I did have to change it to `rtr-listen = ["[::]:3323"]` in order to get it to listen on both. Makes sense as a default, thanks!
