### ISSUE TITLE
routinator_serial_info metric is sparse

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator#941]
As a publication point operator I want to alert when my repository is not updating. For this I use an alert on the `routinator_serial_info` metric.

_When doing so we sometimes hit a weird interaction between prometheus and this sparse metric_, that we have worked around for now with a recording rule.

In practice this metric is sparse (it is empty when notification.xml is not modified). This causes `increase` alerts to fire (see the attached screenshots).

**Expected behaviour**: I expect `routinator_serial_info` to retain the old value when the notification file is not modified.

As discussed in DM with Martin: low priority/low impact, but nice to have.

![preview](https://github.com/NLnetLabs/routinator/assets/199058/c8244e1e-1f45-4853-a5cd-73d5248243c1)
 
<img width="1474" alt="Screenshot_2024-03-08_at_08 35 46" src="https://github.com/NLnetLabs/routinator/assets/199058/36ae74a7-af66-464a-b520-40c4e5bbb0ec">

**Comment by partim** [comment]
It’s a low priority/low impact kind of day today, so I just went ahead and fixed it …
