### ISSUE TITLE
route6:

### ISSUE THREAD

**Issue by matsm** [NLnetLabs/routinator#95]
Hi

When generating a rpsl output (routinator vrps --format rpsl --output /tmp/20190320-0804.rpsl) I get: 

[...]
route: 2001:67c:16d0::/47
origin: AS44574
descr: RPKI attestation
mnt-by: NA
created: 2019-03-20T07:25:28.285693328+00:00
last-modified: 2019-03-20T07:25:28.285693328+00:00
source: ROA-RIPE-RPKI-ROOT
[...]

I have tools that expect the label to be route6: för IPv6 prefixes
Is that possible to make?

/mm

**Comment by partim** [comment]
Oops, my bad. Of course!

**Comment by matsm** [comment]
Thanks for the fix.

Works fine!

A small “feature request" : Is it possible to not have CRLF, LF as  line terminators in the rpsl file

I would like to just have “standard” unix LF?

/mm

**Comment by partim** [comment]
Looks like `whois` in practice does indeed use LF as a line terminator. Who knew. I'll change it.
