### ISSUE TITLE
New UI has clickable column headings that do nothing

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/routinator#969]
In the 0.4.2 UI included in the 0.14.0-rc3 build of Routinator on the Connections tab the tables contain column headings that appear to be clickable (in that the mouse cursor changes to a hand when they are hovered over), e.g. URL, Duration, Status, etc.

However, clicking them doesn't have any noticeable effect. I would expect either that the cursor remains a pointer instead of becoming a hand, or that clicking the column heading changes the sort order of the table.

**Comment by DonOtuseGH** [comment]
same for 0.14.0, release some hours ago...

**Comment by partim** [comment]
This issue should really be in the [routinator-ui repository](https://github.com/NLnetLabs/routinator-ui/). I have created [issue #68](https://github.com/NLnetLabs/routinator-ui/issues/68) there and will close this one.
