### ISSUE TITLE
remove spaces from the input field

### ISSUE THREAD

**Issue by aliofds** [NLnetLabs/routinator#974]
The routinator software does not remove spaces from the input field. so its cause invalid response and not give correct information

**Comment by partim** [comment]
Thank you for your report! However, can you be a bit more specific what input field you are talking about?

**Comment by aliofds** [comment]
Hi Partim, 

I tried to validate my subnet [185.136.148.0/23] using (http://rpki-validator.ripe.net/) but it always failed to give a response after multiple checks, I found there was a space before the IP address I needed to check " 185.136.148.0/23" once I removed the space the link return correct information

**Comment by partim** [comment]
Ah, yes. I have opened an [issue](https://github.com/NLnetLabs/routinator-ui/issues/64) in the routinator-ui project for the matter.

**Comment by partim** [comment]
I’m closing the issue here – we continue in routinator-ui.
